---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/source.toolkit.fluxcd.io/ocirepository_v1.json
apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: echo
spec:
  interval: 15m
  layerSelector:
    mediaType: application/vnd.cncf.helm.chart.content.v1.tar+gzip
    operation: copy
  ref:
    tag: 0.2.4
    digest: sha256:f9bfb2d56c9826cd56caaab11b37977ca5c837721a226a871782080eb61e818a
  url: oci://ghcr.io/home-operations/charts/echo
