{
 "title": "Intel XPU Manager v2 Exporter",
 "tags": [ "xpum" ],
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "Metrics", "label": "Metrics", "query": "prometheus" },
   { "name": "Node", "label": "Node", "query": { "query": "label_values(hw_gpu_info,node)" } }
  ]
 },
 "panels": [
  {
   "title": "GPU Utilization",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "avg by (pci_bdf) (hw_gpu_utilization_ratio{node=\"$Node\"})",
     "legendFormat": "{{pci_bdf}}/{{com_intel_subdevice_id}}"
    }
   ]
  },
  {
   "title": "GPU Utilization",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 4, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg by (pci_bdf) (hw_gpu_utilization_ratio{node=\"$Node\"})",
     "legendFormat": "{{pci_bdf}}/{{com_intel_subdevice_id}}"
    }
   ]
  },
  {
   "title": "GPU Frequency",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "rothz" } },
   "targets": [
    {
     "expr": "hw_frequency_hertz{aggregation=\"avg\", node=\"$Node\"}",
     "legendFormat": "{{pci_bdf}}/{{com_intel_subdevice_id}}: {{hw_frequency_domain}}"
    }
   ]
  },
  {
   "title": "GPU Frequency",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 4, "x": 20, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "rothz" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "hw_frequency_hertz{aggregation=\"avg\", node=\"$Node\"}",
     "legendFormat": "{{pci_bdf}}/{{com_intel_subdevice_id}}: {{hw_frequency_domain}}"
    }
   ]
  },
  {
   "title": "GPU Temperature",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "expr": "hw_temperature_celsius{statistic=\"min\",node=\"$Node\", hw_sensor_location=\"gpu\"}",
     "legendFormat": "min: {{pci_bdf}}/{{com_intel_subdevice_id}}"
    },
    {
     "expr": "hw_temperature_celsius{statistic=\"max\",node=\"$Node\", hw_sensor_location=\"gpu\"}",
     "legendFormat": "max: {{pci_bdf}}/{{com_intel_subdevice_id}}"
    }
   ]
  },
  {
   "title": "GPU Temperature",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 4, "x": 8, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "hw_temperature_celsius{statistic=\"min\",node=\"$Node\", hw_sensor_location=\"gpu\"}",
     "legendFormat": "min: {{pci_bdf}}/{{com_intel_subdevice_id}}"
    },
    {
     "expr": "hw_temperature_celsius{statistic=\"max\",node=\"$Node\", hw_sensor_location=\"gpu\"}",
     "legendFormat": "max: {{pci_bdf}}/{{com_intel_subdevice_id}}"
    }
   ]
  },
  {
   "title": "Memory Temperature",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 12, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "expr": "hw_temperature_celsius{statistic=\"min\",node=\"$Node\", hw_sensor_location=\"memory\"}",
     "legendFormat": "min: {{pci_bdf}}/{{com_intel_subdevice_id}}"
    },
    {
     "expr": "hw_temperature_celsius{statistic=\"max\",node=\"$Node\", hw_sensor_location=\"memory\"}",
     "legendFormat": "max: {{pci_bdf}}/{{com_intel_subdevice_id}}"
    }
   ]
  },
  {
   "title": "Memory Temperature",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 4, "x": 20, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "hw_temperature_celsius{statistic=\"min\",node=\"$Node\", hw_sensor_location=\"memory\"}",
     "legendFormat": "min: {{pci_bdf}}/{{com_intel_subdevice_id}}"
    },
    {
     "expr": "hw_temperature_celsius{statistic=\"max\",node=\"$Node\", hw_sensor_location=\"memory\"}",
     "legendFormat": "max: {{pci_bdf}}/{{com_intel_subdevice_id}}"
    }
   ]
  },
  {
   "title": "Power",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "targets": [
    {
     "expr": "hw_power_watts{node=\"$Node\"}",
     "legendFormat": "{{pci_bdf}}/{{com_intel_subdevice_id}}: {{hw_sensor_location}}"
    }
   ]
  },
  {
   "title": "Power",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 4, "x": 8, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "hw_power_watts{node=\"$Node\"}",
     "legendFormat": "{{pci_bdf}}/{{com_intel_subdevice_id}}: {{hw_sensor_location}}"
    }
   ]
  },
  {
   "title": "Energy",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 12, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "joule" } },
   "targets": [
    {
     "expr": "hw_energy_joules_total{node=\"$Node\"}",
     "legendFormat": "{{pci_bdf}}/{{com_intel_subdevice_id}}: {{hw_sensor_location}}"
    }
   ]
  },
  {
   "title": "Energy",
   "type": "stat",
   "gridPos": { "h": 7, "w": 4, "x": 20, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "joule" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "hw_energy_joules_total{node=\"$Node\"}",
     "legendFormat": "{{pci_bdf}}/{{com_intel_subdevice_id}}: {{hw_sensor_location}}"
    }
   ]
  },
  {
   "title": "Memory Used",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "hw_memory_usage_bytes{node=\"$Node\"}",
     "legendFormat": "{{pci_bdf}}/{{com_intel_subdevice_id}}"
    }
   ]
  },
  {
   "title": "Memory Read",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "hw_memory_io_bytes_total{network_io_direction=\"receive\",node=\"$Node\"}",
     "legendFormat": "{{pci_bdf}}/{{com_intel_subdevice_id}}"
    }
   ]
  },
  {
   "title": "Mem Read Throughput",
   "type": "stat",
   "gridPos": { "h": 7, "w": 3, "x": 12, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rate(hw_memory_io_bytes_total{network_io_direction=\"receive\",node=\"$Node\"}[10s])",
     "legendFormat": "{{pci_bdf}}/{{com_intel_subdevice_id}}"
    }
   ]
  },
  {
   "title": "Memory Write",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 15, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "hw_memory_io_bytes_total{network_io_direction=\"transmit\",node=\"$Node\"}",
     "legendFormat": "{{pci_bdf}}/{{com_intel_subdevice_id}}"
    }
   ]
  },
  {
   "title": "Mem Write Throughput",
   "type": "stat",
   "gridPos": { "h": 7, "w": 3, "x": 21, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rate(hw_memory_io_bytes_total{network_io_direction=\"transmit\",node=\"$Node\"}[10s])",
     "legendFormat": "{{pci_bdf}}/{{com_intel_subdevice_id}}"
    }
   ]
  },
  {
   "title": "Memory Utilization",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "hw_memory_usage_bytes{node=\"$Node\"}/hw_memory_size_bytes{node=\"$Node\"}",
     "legendFormat": "{{pci_bdf}}/{{com_intel_subdevice_id}}"
    }
   ]
  },
  {
   "title": "PCIe Read",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "hw_gpu_io_bytes_total{network_io_direction=\"receive\",node=\"$Node\"}",
     "legendFormat": "{{pci_bdf}}/{{com_intel_subdevice_id}}"
    }
   ]
  },
  {
   "title": "PCIe Read Throughput",
   "type": "stat",
   "gridPos": { "h": 7, "w": 3, "x": 12, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rate(hw_gpu_io_bytes_total{network_io_direction=\"receive\",node=\"$Node\"}[10s])",
     "legendFormat": "{{pci_bdf}}/{{com_intel_subdevice_id}}"
    }
   ]
  },
  {
   "title": "PCIe Write",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 15, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "hw_gpu_io_bytes_total{network_io_direction=\"transmit\",node=\"$Node\"}",
     "legendFormat": "{{pci_bdf}}/{{com_intel_subdevice_id}}"
    }
   ]
  },
  {
   "title": "PCIe Write Throughput",
   "type": "stat",
   "gridPos": { "h": 7, "w": 3, "x": 21, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rate(hw_gpu_io_bytes_total{network_io_direction=\"transmit\",node=\"$Node\"}[10s])",
     "legendFormat": "{{pci_bdf}}/{{com_intel_subdevice_id}}"
    }
   ]
  },
  {
   "title": "Memory Bandwidth",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "hw_memory_bandwidth_utilization_ratio{node=\"$Node\"}",
     "legendFormat": "{{pci_bdf}}/{{com_intel_subdevice_id}}"
    }
   ]
  },
  {
   "title": "Engine Group Utilization",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "avg by (pci_bdf,hw_gpu_task) (hw_gpu_utilization_ratio{node=\"$Node\"})",
     "legendFormat": "{{pci_bdf}}/{{com_intel_subdevice_id}}: {{hw_gpu_task}}"
    }
   ]
  },
  {
   "title": "Per Engine Utilization",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "hw_gpu_utilization_ratio{node=\"$Node\"}",
     "legendFormat": "{{pci_bdf}}/{{com_intel_subdevice_id}}: {{hw_name}}"
    }
   ]
  }
 ]
}