---
# yaml-language-server: $schema=https://kubernetes-schemas.dmfrey.com/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: xpumd
spec:
  chartRef:
    kind: OCIRepository
    name: xpumd
  interval: 1h
  values:
    image:
      tag: v2.0.0-rc.0
    gpuAccess: dra
    nodeSelector:
      node.kubernetes.io/gpu: "true"
    prometheus:
      monitor: true
      release: kube-prometheus-stack
    grafana:
      dashboards: true
      namespace: observability
  postRenderers:
    - kustomize:
        patches:
          - patch: |-
              - op: replace
                path: /metadata/labels/app.kubernetes.io~1version
                value: 2.0.0-rc.0
            target:
              labelSelector: "app.kubernetes.io/instance=xpumd"
