---
# yaml-language-server: $schema=https://kubernetes-schemas.dmfrey.com/grafana.integreatly.org/grafanadatasource_v1beta1.json
apiVersion: grafana.integreatly.org/v1beta1
kind: GrafanaDatasource
metadata:
  name: prometheus
spec:
  instanceSelector:
    matchLabels:
      grafana.internal/instance: grafana
  datasource:
    type: prometheus
    name: prometheus
    access: proxy
    isDefault: true
    url: http://prometheus-operated.observability.svc.cluster.local:9090
---
# yaml-language-server: $schema=https://kubernetes-schemas.dmfrey.com/grafana.integreatly.org/grafanadatasource_v1beta1.json
apiVersion: grafana.integreatly.org/v1beta1
kind: GrafanaDatasource
metadata:
  name: alertmanager
spec:
  instanceSelector:
    matchLabels:
      grafana.internal/instance: grafana
  datasource:
    type: alertmanager
    name: alertmanager
    access: proxy
    jsonData:
      implementation: prometheus
    url: http://alertmanager-operated.observability.svc.cluster.local:9093
---
# yaml-language-server: $schema=https://kubernetes-schemas.dmfrey.com/grafana.integreatly.org/grafanadatasource_v1beta1.json
apiVersion: grafana.integreatly.org/v1beta1
kind: GrafanaDatasource
metadata:
  name: loki
spec:
  instanceSelector:
    matchLabels:
      grafana.internal/instance: grafana
  datasource:
    type: loki
    name: loki
    access: proxy
    url: http://loki-gateway.observability.svc.cluster.local:80
    jsonData:
      derivedFields:
        - name: TraceID
          matcherRegex: '"traceId"\s*:\s*"([a-f0-9]+)"'
          datasourceUid: tempo
          urlDisplayLabel: View Trace
        - name: TraceID-text
          matcherRegex: 'traceId=([a-f0-9]+)'
          datasourceUid: tempo
          urlDisplayLabel: View Trace
---
# yaml-language-server: $schema=https://kubernetes-schemas.dmfrey.com/grafana.integreatly.org/grafanadatasource_v1beta1.json
apiVersion: grafana.integreatly.org/v1beta1
kind: GrafanaDatasource
metadata:
  name: tempo
spec:
  instanceSelector:
    matchLabels:
      grafana.internal/instance: grafana
  datasource:
    type: tempo
    name: tempo
    uid: tempo
    access: proxy
    url: http://tempo.observability.svc.cluster.local:3100
    jsonData:
      tracesToLogsV2:
        datasourceUid: loki
        filterByTraceID: true
        filterBySpanID: true
      tracesToMetrics:
        datasourceUid: prometheus
      nodeGraph:
        enabled: true
      serviceMap:
        datasourceUid: prometheus
