---
# yaml-language-server: $schema=https://kubernetes-schemas.dmfrey.com/source.toolkit.fluxcd.io/ocirepository_v1.json
apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: rook-ceph-cluster
spec:
  interval: 15m
  layerSelector:
    mediaType: application/vnd.cncf.helm.chart.content.v1.tar+gzip
    operation: copy
  ref:
    tag: v1.20.4
    digest: sha256:ed24cdb6e7c1f8b67a738ca28b6d11a774805834b9d678e71ba812afc6a5f1d8
  url: oci://ghcr.io/rook/rook-ceph-cluster
