---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: ${APP}-dragonfly-unstick
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: ${APP}-dragonfly-unstick
rules:
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["get", "list", "delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: ${APP}-dragonfly-unstick
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: ${APP}-dragonfly-unstick
subjects:
  - kind: ServiceAccount
    name: ${APP}-dragonfly-unstick
