---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/source.toolkit.fluxcd.io/ocirepository_v1.json
apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: kube-prometheus-stack
spec:
  interval: 15m
  layerSelector:
    mediaType: application/vnd.cncf.helm.chart.content.v1.tar+gzip
    operation: copy
  ref:
    tag: 91.8.1
    digest: sha256:3cb1af8f63ff3861c8782c78f79761b799bc589b2f9b434594fec90acf986fc8
  url: oci://ghcr.io/prometheus-community/charts/kube-prometheus-stack
