---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/source.toolkit.fluxcd.io/ocirepository_v1.json
apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: kube-prometheus-stack
spec:
  interval: 15m
  layerSelector:
    mediaType: application/vnd.cncf.helm.chart.content.v1.tar+gzip
    operation: copy
  ref:
    tag: 92.1.1
    digest: sha256:d70396ef589f28581e5e86d801b7952372c561a03d6c6fd5b6ac953d90a23049
  url: oci://ghcr.io/prometheus-community/charts/kube-prometheus-stack
