---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/source.toolkit.fluxcd.io/ocirepository_v1.json
apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: kube-prometheus-stack
spec:
  interval: 15m
  layerSelector:
    mediaType: application/vnd.cncf.helm.chart.content.v1.tar+gzip
    operation: copy
  ref:
    tag: 91.5.1
    digest: sha256:860a587ea62f3c5910479d4ac012d8fa2d22c2cb91c9b0e03ff3739e17d25dc0
  url: oci://ghcr.io/prometheus-community/charts/kube-prometheus-stack
