---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: opencode
spec:
  components:
    - ../../../../components/kopiur/backup
  dependsOn:
    - name: rook-ceph-cluster
      namespace: rook-ceph
    - name: kopiur-repository
      namespace: kopiur-system
  interval: 1h
  path: "./kubernetes/apps/ai/opencode/app"
  prune: true
  postBuild:
    substitute:
      APP: opencode
      KOPIUR_CAPACITY: 2Gi
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  targetNamespace: ai
  wait: true
