[pre-commit.commands.yamlfmt]
glob = "*.{yaml,yml}"
run = "yamlfmt {staged_files}"
stage_fixed = true

[pre-commit.commands.just-fmt]
glob = "*.just"
run = "just --fmt --unstable -f {staged_files}"
stage_fixed = true
