[env]
KUBECONFIG = "{{config_root | canonicalize}}/kubeconfig"
MINIJINJA_CONFIG_FILE = "{{config_root | canonicalize}}/.minijinja.toml"
TALOSCONFIG = "{{config_root | canonicalize}}/talosconfig"
LEFTHOOK_OUTPUT = "false"

_.file = [
  "{{config_root}}/onepassword.env"
]

[hooks]
enter = "just doctor"

[tools]
"just" = "latest"
"uv" = "latest"
"pipx:flux-local" = "latest"
