apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: node-debugger-ds
spec:
  selector:
    matchLabels:
      app: node-debugger
  template:
    metadata:
      labels:
        app: node-debugger
    spec:
      tolerations:
      - operator: "Exists"
      containers:
      - name: debugger
        image: ubuntu:24.04
        command: ["/bin/sh", "-c", "apt-get update && apt-get install -y nvme-cli procps && sleep 36000"]
        securityContext:
          privileged: true
        volumeMounts:
        - name: host-root
          mountPath: /host
          readOnly: true
        - name: dev-mount
          mountPath: /dev
      volumes:
      - name: host-root
        hostPath:
          path: /
      - name: dev-mount
        hostPath:
          path: /dev