---
# yaml-language-server: $schema=https://kubernetes-schemas.dmfrey.com/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: prometheus-adapter
spec:
  chartRef:
    kind: OCIRepository
    name: prometheus-adapter
  interval: 1h
  values:
    replicas: 2
    podDisruptionBudget:
      enabled: true
      minAvailable: 1
      maxUnavailable: null
    affinity:
      podAntiAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
                - key: app.kubernetes.io/name
                  operator: In
                  values:
                    - prometheus-adapter
            topologyKey: kubernetes.io/hostname
    prometheus:
      url: http://prometheus-operated.observability.svc.cluster.local
      port: 9090
    rules:
      default: false
      external:
        - seriesQuery: '{__name__="probe_success"}'
          resources:
            namespaced: false
          name:
            as: probe_success
          metricsQuery: max_over_time(<<.Series>>{<<.LabelMatchers>>}[1m])
