{
 "title": "Gatus",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "Total results per minute",
   "type": "timeseries",
   "description": "Number of results per minute",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(gatus_results_total[5m])*60) by (name)",
     "legendFormat": "{{ name }}"
    }
   ]
  },
  {
   "title": "Successful results per minute",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "sum(rate(gatus_results_total{success=\"true\"}[5m])*60) by (name)",
     "legendFormat": "{{ name }}"
    }
   ]
  },
  {
   "title": "Unsuccessful results",
   "type": "stat",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rate(gatus_results_total{success=\"false\"}[1m])*60"
    }
   ]
  },
  {
   "title": "Unsuccessful results per minute",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(gatus_results_total{success=\"false\"}[5m])*60) by (name)",
     "legendFormat": "{{ name }} "
    }
   ]
  }
 ]
}