---
# yaml-language-server: $schema=https://kubernetes-schemas.dmfrey.com/postgresql.cnpg.io/database_v1.json
apiVersion: postgresql.cnpg.io/v1
kind: Database
metadata:
  name: lidarr-log
spec:
  name: lidarr-log
  owner: lidarr
  cluster:
    name: lidarr-cnpg
