---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/source.toolkit.fluxcd.io/ocirepository_v1.json
apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: descheduler
spec:
  interval: 15m
  layerSelector:
    mediaType: application/vnd.cncf.helm.chart.content.v1.tar+gzip
    operation: copy
  ref:
    tag: 0.37.0
    digest: sha256:6b8dbb8247bdc3b244e997768b0a3002b72e897b3f759dda7ce488de7181478f
  url: oci://ghcr.io/home-operations/charts-mirror/descheduler
