---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/source.toolkit.fluxcd.io/ocirepository_v1.json
apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: coredns
spec:
  interval: 15m
  layerSelector:
    mediaType: application/vnd.cncf.helm.chart.content.v1.tar+gzip
    operation: copy
  ref:
    tag: 1.48.2
    digest: sha256:00beff4767c97f87bc5195d0e03d782939999a2c3f5b12cc468b469fb90151fb
  url: oci://ghcr.io/coredns/charts/coredns
