---
# yaml-language-server: $schema=https://kubernetes-schemas.dmfrey.com/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: dependency-track-db
spec:
  dependsOn:
    - name: cloudnative-pg
      namespace: datastore
    - name: rook-ceph-cluster
      namespace: rook-ceph
  healthChecks:
    - apiVersion: postgresql.cnpg.io/v1
      kind: Cluster
      name: dependency-track-cnpg
      namespace: security
  interval: 1h
  path: "./kubernetes/apps/security/dependency-track/dependency-track-db"
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  targetNamespace: security
  wait: false
---
# yaml-language-server: $schema=https://kubernetes-schemas.dmfrey.com/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: dependency-track
spec:
  components:
    - ../../../../components/nfs-scaler
    - ../../../../components/volsync
  dependsOn:
    - name: dependency-track-db
  healthChecks:
    - apiVersion: helm.toolkit.fluxcd.io/v2
      kind: HelmRelease
      name: dependency-track
      namespace: security
  interval: 1h
  path: "./kubernetes/apps/security/dependency-track/app"
  postBuild:
    substitute:
      APP: dependency-track
      NFS_SCALER_TARGET: dependency-track-api
      VOLSYNC_CAPACITY: 10Gi
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  targetNamespace: security
  wait: true
