---
# yaml-language-server: $schema=https://kubernetes-schemas.dmfrey.com/infra.contrib.fluxcd.io/terraform_v1alpha2.json
apiVersion: infra.contrib.fluxcd.io/v1alpha2
kind: Terraform
metadata:
  name: authentik-provisioner
spec:

  approvePlan: auto
  interval: 15m
  path: "./"

  sourceRef:
    kind: OCIRepository
    name: oci-terraform-authentik

  writeOutputsToSecret:
    name: authentik-tfstate

  varsFrom:
    - kind: Secret
      name: terraform-secret

  vars:
    - name: CLUSTER_DOMAIN
      value: dmfrey.com
