---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/source.toolkit.fluxcd.io/ocirepository_v1.json
apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: chaski
spec:
  interval: 15m
  layerSelector:
    mediaType: application/vnd.cncf.helm.chart.content.v1.tar+gzip
    operation: copy
  ref:
    tag: 0.5.1
    digest: sha256:3660e79b8c1bea2e1ddb45477bd4621024482b4a8fda8d192ec1a22c20969405
  url: oci://ghcr.io/home-operations/charts/chaski
