---
# yaml-language-server: $schema=https://kubernetes-schemas.dmfrey.com/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: garage
spec:
  secretStoreRef:
    name: onepassword
    kind: ClusterSecretStore
  refreshInterval: 15m
  target:
    name: garage-secret
    template:
      engineVersion: v2
      data:
        RPC_SECRET: "{{ .RPC_SECRET }}"
        ADMIN_TOKEN: "{{ .ADMIN_TOKEN }}"
  dataFrom:
    - extract:
        key: garage
