---
# yaml-language-server: $schema=https://kubernetes-schemas.dmfrey.com/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: garage
spec:
  secretStoreRef:
    name: onepassword
    kind: ClusterSecretStore
  refreshInterval: 15m
  target:
    name: garage-secret
    template:
      engineVersion: v2
      data:
        GARAGE_RPC_SECRET: "{{ .GARAGE_RPC_SECRET | trim }}"
        GARAGE_ADMIN_TOKEN: "{{ .GARAGE_ADMIN_TOKEN | trim }}"
        GARAGE_METRICS_TOKEN: "{{ .GARAGE_METRICS_TOKEN | trim }}"
  dataFrom:
    - extract:
        key: garage
