---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: openweb-db
spec:
  dependsOn:
    - name: cloudnative-pg
      namespace: datastore
  healthChecks:
    - apiVersion: postgresql.cnpg.io/v1
      kind: Cluster
      name: openweb-cnpg
      namespace: ai
  interval: 1h
  path: "./kubernetes/apps/ai/openweb/openweb-db"
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  targetNamespace: ai
  wait: false
---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: openweb-kv
spec:
  dependsOn:
    - name: dragonfly-operator
      namespace: datastore
    - name: garage
      namespace: garage-system
    - name: rook-ceph-cluster
      namespace: rook-ceph
  healthChecks:
    - apiVersion: dragonflydb.io/v1alpha1
      kind: Dragonfly
      name: openweb-dragonflydb
      namespace: ai
  interval: 1h
  path: "./kubernetes/apps/ai/openweb/openweb-kv"
  postBuild:
    substitute:
      APP: openweb
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  targetNamespace: ai
  wait: false
---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: openweb
spec:
  components:
    - ../../../../components/nfs-scaler
    - ../../../../components/volsync
    - ../../../../components/kopiur/policy
  dependsOn:
    - name: openweb-db
    - name: openweb-kv
    - name: rook-ceph-cluster
      namespace: rook-ceph
    - name: kopiur-repository
      namespace: kopiur-system
  interval: 1h
  path: "./kubernetes/apps/ai/openweb/app"
  postBuild:
    substitute:
      APP: openweb
      CONTROLLER: StatefulSet
      VOLSYNC_CAPACITY: 2Gi
      KOPIUR_PUID: "0"
      KOPIUR_PGID: "0"
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  targetNamespace: ai
  wait: true
