---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: sonarr

spec:
  chartRef:
    kind: OCIRepository
    name: sonarr

  interval: 1h

  values:
    controllers:
      sonarr:
        type: statefulset

        annotations:
          reloader.stakater.com/auto: "true"

        containers:
          app:
            image:
              repository: ghcr.io/home-operations/sonarr
              tag: 4.0.19.3006@sha256:f3f87b789aca4e27eb60401e0782200b351b727d3b55d42279dbfb4b24f00d9c

            env:
              TZ: America/New_York
              SONARR__INSTANCE_NAME: sonarr
              SONARR__PORT: &port 8989
              SONARR__APPLICATION_URL: https://sonarr.dmfrey.com
              SONARR__LOG_LEVEL: info
              SONARR__ANALYTICS_ENABLED: "False"
              SONARR__AUTHENTICATION_METHOD: External
              SONARR__API_KEY:
                valueFrom:
                  secretKeyRef:
                    name: sonarr-secret
                    key: SONARR_API_KEY

            probes:
              liveness: &probes
                enabled: true
                custom: true
                spec:
                  httpGet:
                    path: /ping
                    port: *port
                  initialDelaySeconds: 0
                  periodSeconds: 10
                  timeoutSeconds: 1
                  failureThreshold: 3
              readiness: *probes

            resources:
              requests:
                cpu: 10m
              limits:
                memory: 350Mi

            securityContext:
              allowPrivilegeEscalation: false
              readOnlyRootFilesystem: true
              capabilities:
                drop:
                  - ALL

    defaultPodOptions:
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
        fsGroupChangePolicy: OnRootMismatch

    service:
      app:
        ports:
          http:
            port: *port

    route:
      app:
        hostnames:
          - "{{ .Release.Name }}.dmfrey.com"
        annotations:
          gethomepage.dev/enabled: "true"
          gethomepage.dev/group: Downloads
          gethomepage.dev/name: Sonarr
          gethomepage.dev/icon: sonarr.png
          gethomepage.dev/description: TV Downloads
          gethomepage.dev/widget.type: sonarr
          gethomepage.dev/widget.url: http://sonarr.media.svc.cluster.local:8989
          gethomepage.dev/widget.key: "{{ `{{HOMEPAGE_VAR_SONARR_TOKEN}}` }}"
        parentRefs:
          - name: envoy-internal
            namespace: network
      outpost:
        hostnames:
          - "{{ .Release.Name }}.dmfrey.com"
        parentRefs:
          - name: envoy-internal
            namespace: network
        rules:
          - matches:
              - path:
                  type: PathPrefix
                  value: /outpost.goauthentik.io
            backendRefs:
              - name: ak-outpost-authentik-embedded-outpost
                namespace: security
                port: 9000

    persistence:
      config:
        existingClaim: "{{ .Release.Name }}"

      media:
        type: nfs
        server: nas.internal
        path: /media

      backups:
        enabled: true
        type: nfs
        server: nas.internal
        path: /plexbackups/backups/sonarr
        advancedMounts:
          sonarr:
            app:
              - path: /config/Backups

      tmp:
        type: emptyDir
        medium: Memory
        advancedMounts:
          sonarr:
            app:
              - path: /tmp
