---
# yaml-language-server: $schema=https://raw.githubusercontent.com/datreeio/CRDs-catalog/main/rabbitmq.com/rabbitmqcluster_v1beta1.json
apiVersion: rabbitmq.com/v1beta1
kind: RabbitmqCluster
metadata:
  name: spring-notes-rabbitmq
spec:
  replicas: 1
  # renovate: datasource=docker depName=rabbitmq versioning=loose
  image: rabbitmq:4.3-management@sha256:1d7dfbe6c30e04f0a130a1d6e1b31028fe8245c7033c09ffb6ea6554b8fdb2f0
  resources:
    requests:
      cpu: 100m
      memory: 256Mi
    limits:
      cpu: 500m
      memory: 512Mi
  persistence:
    storageClassName: ceph-block
    storage: 2Gi
