---
# yaml-language-server: $schema=https://kubernetes-schemas.dmfrey.com/rabbitmq.com/rabbitmqcluster_v1beta1.json
apiVersion: rabbitmq.com/v1beta1
kind: RabbitmqCluster
metadata:
  name: spring-notes-rabbitmq
spec:
  replicas: 1
  # renovate: datasource=docker depName=rabbitmq versioning=loose
  image: rabbitmq:4.3-management@sha256:06fb591136a49e861e01aaaf9ce45085839ca23c35913d45a1e83519bb9778ca
  resources:
    requests:
      cpu: 100m
      memory: 256Mi
    limits:
      cpu: 500m
      memory: 512Mi
  persistence:
    storageClassName: ceph-block
    storage: 2Gi
