---
# yaml-language-server: $schema=https://kubernetes-schemas.dmfrey.com/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: immich
spec:
  secretStoreRef:
    name: onepassword
    kind: ClusterSecretStore
  refreshInterval: 15m
  target:
    name: immich-secret
    template:
      engineVersion: v2
      data:
        immich-config.json: |
          {
            "machineLearning": {
              "urls": ["http://immich-machine-learning.self-hosted.svc.cluster.local:3003"]
            },
            "metadata": {
              "faces": {
                "import": true
              }
            },
            "oauth": {
              "enabled": true,
              "autoRegister": true,
              "buttonText": "Login with Authentik",
              "clientId": "{{ .AUTHENTIK_CLIENT_ID }}",
              "clientSecret": "{{ .AUTHENTIK_CLIENT_SECRET }}",
              "issuerUrl": "https://auth.dmfrey.com/application/o/immich/",
              "roleClaim": "immich_role"
            },
            "notifications": {
              "smtp": {
                "enabled": true,
                "from": "No Reply <noreply@homelab5767.cc>",
                "transport": {
                  "host": "smtp-relay.kube-system.svc.cluster.local",
                  "port": 25,
                  "secure": false,
                  "ignoreCert": false
                }
              }
            }
          }
  dataFrom:
  - extract:
      key: immich
