---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: matter-server
spec:
  components:
    - ../../../../components/nfs-scaler
    - ../../../../components/volsync
    - ../../../../components/kopiur/policy
  dependsOn:
    - name: rook-ceph-cluster
      namespace: rook-ceph
    - name: kopiur-repository
      namespace: kopiur-system
  interval: 1h
  path: "./kubernetes/apps/home/matter-server/app"
  postBuild:
    substitute:
      APP: matter-server
      CONTROLLER: StatefulSet
      VOLSYNC_CAPACITY: 5Gi
      KOPIUR_PUID: "0"
      KOPIUR_PGID: "0"
    substituteFrom:
      - kind: Secret
        name: cluster-secrets
        optional: false
  prune: true
  retryInterval: 2m
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  targetNamespace: home
  wait: false
