---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/source.toolkit.fluxcd.io/ocirepository_v1.json
apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: alloy
spec:
  interval: 15m
  layerSelector:
    mediaType: application/vnd.cncf.helm.chart.content.v1.tar+gzip
    operation: copy
  ref:
    tag: 1.13.0
    digest: sha256:925195b32bd1c969b29a5b8b4765ccb677d76a26bad2bf558a6e88e9a8d63969
  url: oci://ghcr.io/home-operations/charts-mirror/alloy
