---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/source.toolkit.fluxcd.io/ocirepository_v1.json
apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: alloy
spec:
  interval: 15m
  layerSelector:
    mediaType: application/vnd.cncf.helm.chart.content.v1.tar+gzip
    operation: copy
  ref:
    tag: 1.12.1
    digest: sha256:051d839c713ea0faaa60852dcd89498e9d29d22060201e35471e410bfc1f95fb
  url: oci://ghcr.io/home-operations/charts-mirror/alloy
