---
# yaml-language-server: $schema=https://kubernetes-schemas.dmfrey.com/gateway.networking.k8s.io/referencegrant_v1beta1.json
apiVersion: gateway.networking.k8s.io/v1beta1
kind: ReferenceGrant
metadata:
  name: envoy-tracing-alloy
  namespace: observability
spec:
  from:
    - group: gateway.envoyproxy.io
      kind: EnvoyProxy
      namespace: network
  to:
    - group: ""
      kind: Service
      name: alloy
