---
# yaml-language-server: $schema=https://kubernetes-schemas.dmfrey.com/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: authentik
spec:
  chartRef:
    kind: OCIRepository
    name: authentik
  interval: 1h
  values:
    global:
      storageClass: ceph-block
      image:
        repository: ghcr.io/goauthentik/server
        tag: 2026.5.6
        pullPolicy: IfNotPresent
      envFrom:
        - secretRef:
            name: authentik-secret
    authentik:
      security_key: ""
      avatars: "gravatar,initials"
      log_level: info
      email:
        host: smtp-relay.kube-system.svc.cluster.local
        port: 25
        use_tls: false
        from: noreply@homelab5767.cc
      error_reporting:
        enabled: false
        send_pii: false
      postgresql:
        host: file:///postgres-creds/host
        port: 5432
        user: file:///postgres-creds/username
        password: file:///postgres-creds/password
      redis:
        host: authentik-dragonflydb.security.svc.cluster.local
    geoip:
      enabled: true
      existingSecret:
        secretName: authentik-secret
        accountId: MAXMIND_ACCOUNT_ID
        licenseKey: MAXMIND_LICENSE_KEY
      editionIds: "GeoLite2-City"
      image:
        repository: ghcr.io/maxmind/geoipupdate
        tag: v8.0.0
      updateInterval: 8
      resources:
        requests:
          cpu: 50m
        limits:
          memory: 512Mi
    prometheus:
      rules:
        enabled: true
    server:
      autoscaling:
        enabled: true
        minReplicas: 2
        maxReplicas: 3
      env:
        - name: AUTHENTIK_WEB__MAX_REQUESTS
          value: "100"
        - name: AUTHENTIK_WEB__MAX_REQUESTS_JITTER
          value: "10"
      lifecycle:
        preStop:
          exec:
            command: ["/bin/sh", "-c", "sleep 10"]
      deploymentAnnotations:
        secret.reloader.stakater.com/reload: authentik-cnpg-app
      metrics:
        serviceMonitor:
          enabled: true
      resources:
        requests:
          cpu: 200m
        limits:
          memory: 4Gi
      volumes: &postgresCredsVolume
        - name: postgres-creds
          secret:
            secretName: authentik-cnpg-app
        - name: dshm
          emptyDir:
            medium: Memory
            sizeLimit: 512Mi
      volumeMounts: &postgresCredsVolumeMounts
        - name: postgres-creds
          mountPath: /postgres-creds
          readOnly: true
        - name: dshm
          mountPath: /dev/shm
    worker:
      autoscaling:
        enabled: true
        minReplicas: 2
        maxReplicas: 10
      resources:
        requests:
          cpu: 100m
        limits:
          memory: 1024Mi
      volumes: *postgresCredsVolume
      volumeMounts: *postgresCredsVolumeMounts
