---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/source.toolkit.fluxcd.io/ocirepository_v1.json
apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: authentik
spec:
  interval: 1m
  layerSelector:
    mediaType: application/vnd.cncf.helm.chart.content.v1.tar+gzip
    operation: copy
  ref:
    tag: 2026.8.1
    digest: sha256:2f8a64c2dd236e6449f28843165b41402d77c4eee704e8842e926163e5ce31dc
  url: oci://ghcr.io/goauthentik/helm-charts/authentik
