---
# yaml-language-server: $schema=https://kubernetes-schemas.dmfrey.com/gateway.networking.k8s.io/referencegrant_v1beta1.json
apiVersion: gateway.networking.k8s.io/v1beta1
kind: ReferenceGrant
metadata:
  name: authentik-ext-authz
  namespace: security
spec:
  from:
    - group: gateway.envoyproxy.io
      kind: SecurityPolicy
      namespace: ai
    - group: gateway.networking.k8s.io
      kind: HTTPRoute
      namespace: ai
    - group: gateway.envoyproxy.io
      kind: SecurityPolicy
      namespace: download
    - group: gateway.networking.k8s.io
      kind: HTTPRoute
      namespace: download
    - group: gateway.envoyproxy.io
      kind: SecurityPolicy
      namespace: home
    - group: gateway.networking.k8s.io
      kind: HTTPRoute
      namespace: home
    - group: gateway.envoyproxy.io
      kind: SecurityPolicy
      namespace: media
    - group: gateway.networking.k8s.io
      kind: HTTPRoute
      namespace: media
    - group: gateway.envoyproxy.io
      kind: SecurityPolicy
      namespace: observability
    - group: gateway.networking.k8s.io
      kind: HTTPRoute
      namespace: observability
    - group: gateway.envoyproxy.io
      kind: SecurityPolicy
      namespace: self-hosted
    - group: gateway.networking.k8s.io
      kind: HTTPRoute
      namespace: self-hosted
  to:
    - group: ""
      kind: Service
      name: ak-outpost-authentik-embedded-outpost
