---
# yaml-language-server: $schema=https://kubernetes-schemas.dmfrey.com/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: &name spring-notes-dtrack-secret
spec:
  secretStoreRef:
    name: onepassword
    kind: ClusterSecretStore
  refreshInterval: 15m
  target:
    name: *name
    template:
      engineVersion: v2
      data:
        DEPENDENCY_TRACK_API_KEY: '{{ .DEPENDENCY_TRACK_API_KEY }}'
  dataFrom:
    - extract:
        key: dependency-track
---
# yaml-language-server: $schema=https://kubernetes-schemas.dmfrey.com/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: &name spring-notes-secret
spec:
  secretStoreRef:
    name: onepassword
    kind: ClusterSecretStore
  refreshInterval: 15m
  target:
    name: *name
    template:
      engineVersion: v2
      data:
        AUTHENTIK_CLIENT_ID: '{{ .AUTHENTIK_CLIENT_ID }}'
  dataFrom:
    - extract:
        key: spring-notes
