---
# yaml-language-server: $schema=https://kubernetes-schemas.dmfrey.com/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: &name spring-notes-secret
spec:
  secretStoreRef:
    name: onepassword-connect
    kind: ClusterSecretStore
  refreshInterval: 15m
  target:
    name: *name
    template:
      engineVersion: v2
      data:
        AUTHENTIK_CLIENT_ID: "{{ .AUTHENTIK_CLIENT_ID }}"
  dataFrom:
    - extract:
        key: spring-notes
