---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: reolink-ftp
spec:
  accessModes:
    - ReadWriteMany
  capacity:
    storage: 200Gi
  mountOptions:
    - vers=3
    - nolock
  nfs:
    server: unas.internal
    path: /volume/98306492-ba3e-4373-ba5a-e6e661135f84/.srv/.unifi-drive/reolink/.data
  persistentVolumeReclaimPolicy: Retain
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: reolink-ftp
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 200Gi
  volumeName: reolink-ftp
  storageClassName: ""
