---
# yaml-language-server: $schema=https://kubernetes-schemas.dmfrey.com/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: bambuddy
spec:
  secretStoreRef:
    name: onepassword
    kind: ClusterSecretStore
  refreshInterval: 15m
  target:
    name: bambuddy-secret
    template:
      engineVersion: v2
      data:
        HA_TOKEN: "{{ .HA_TOKEN }}"
  dataFrom:
    - extract:
        key: bambuddy
