---
# yaml-language-server: $schema=https://kubernetes-schemas.dmfrey.com/source.toolkit.fluxcd.io/ocirepository_v1beta2.json
apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: blackbox-exporter-vpn
spec:
  interval: 15m
  layerSelector:
    mediaType: application/vnd.cncf.helm.chart.content.v1.tar+gzip
    operation: copy
  ref:
    tag: 11.17.1
    digest: sha256:5676cd154a47c9b91f0047cc96193566e076dd91604670159e2c5dfdae768b8d
  url: oci://ghcr.io/prometheus-community/charts/prometheus-blackbox-exporter
