---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/source.toolkit.fluxcd.io/ocirepository_v1.json
apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: kopiur
spec:
  interval: 15m
  layerSelector:
    mediaType: application/vnd.cncf.helm.chart.content.v1.tar+gzip
    operation: copy
  ref:
    tag: 0.10.5
    digest: sha256:63095f096cf356999c55f5dc526bd0cf10da619bc1ef6d7a6daf26ae05b74a6f
  url: oci://ghcr.io/home-operations/charts/kopiur
