---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/source.toolkit.fluxcd.io/ocirepository_v1.json
apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: silence-operator
spec:
  interval: 5m
  layerSelector:
    mediaType: application/vnd.cncf.helm.chart.content.v1.tar+gzip
    operation: copy
  ref:
    tag: 0.21.0
    digest: sha256:99509222f3a165e01913f23f684b36c352d5795fbe082812f5b3603cbb76bbea
  url: oci://gsoci.azurecr.io/charts/giantswarm/silence-operator
