---
# yaml-language-server: $schema=https://kubernetes-schemas.dmfrey.com/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: matter-server
spec:

  chartRef:
    kind: OCIRepository
    name: matter-server

  interval: 1h

  values:

    controllers:

      matter-server:
        type: statefulset

        annotations:
          reloader.stakater.com/auto: "true"

        containers:
          app:
            image:
              repository: ghcr.io/matter-js/matterjs-server
              tag: 1.1.3@sha256:c136e497324890b307287db2e035cef5e844ac915ea3de7907e2838324c4478e

            args:
              - --storage-path=/data
              - --primary-interface=net1
              - --log-level=debug

            env:
              TZ: "America/New_York"
              LOG_LEVEL: debug

            resources:
              limits:
                memory: 350Mi

    defaultPodOptions:
      terminationGracePeriodSeconds: 10
      annotations:
        k8s.v1.cni.cncf.io/networks: |
          [{
            "name": "iot-vlan",
            "namespace": "kube-system",
            "ips": ["192.168.50.9/24", "${IPV6_IOT_PREFIX}:9::1/64"],
            "mac": "aa:8c:ae:86:6e:8a"
          }]
      hostUsers: false
      securityContext:
        runAsNonRoot: false # Must be run as root user
        runAsUser: 0        # Must be run as root user
        runAsGroup: 0
        fsGroup: 0
        fsGroupChangePolicy: OnRootMismatch
        supplementalGroups:
          - 34

    service:
      app:
        ports:
          http:
            port: 5580

    persistence:
      data:
        existingClaim: "{{ .Release.Name }}"

      tmp:
        type: emptyDir
