{
 "title": "Tasks",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "15s",
 "templating": {
  "list": [
   { "name": "task_name", "label": "task", "query": "label_values(task_name)" },
   {
    "name": "task_execution_id",
    "label": "task_id",
    "query": "label_values({task_name=\"$task_name\"},task_execution_id)"
   },
   {
    "name": "job_name",
    "label": "job",
    "query": "label_values(spring_batch_job_seconds_max{task_name=\"$task_name\"},name)"
   }
  ]
 },
 "panels": [
  {
   "title": "Task Count",
   "type": "singlestat",
   "description": "Number of executed tasks in this the time range",
   "gridPos": { "h": 4, "w": 2, "x": 0, "y": 0 },
   "format": "none",
   "valueName": "total",
   "targets": [
    {
     "expr": "count(count by (task_name,task_execution_id) (spring_cloud_task_seconds_count))"
    }
   ]
  },
  {
   "title": "Active Tasks Count",
   "type": "graph",
   "description": "Number of executed tasks in this the time range",
   "gridPos": { "h": 8, "w": 10, "x": 2, "y": 0 },
   "targets": [
    {
     "expr": "spring_cloud_task_active_seconds_active_count",
     "legendFormat": "{{task_name}}:{{task_execution_id}}"
    }
   ]
  },
  {
   "title": "Task Duration",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "sum(spring_cloud_task_seconds_sum) by (task_name,task_execution_id)",
     "legendFormat": "{{task_name}}:{{task_execution_id}}"
    }
   ]
  },
  {
   "title": "Job  Count",
   "type": "singlestat",
   "description": "Number of executed tasks in this the time range",
   "gridPos": { "h": 4, "w": 2, "x": 0, "y": 4 },
   "format": "none",
   "valueName": "total",
   "targets": [
    {
     "expr": "count(count(spring_batch_job_active_seconds_active_count) by (task_name,task_execution_id,name))"
    }
   ]
  },
  {
   "title": "Active Task Duration",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "sum(spring_cloud_task_active_seconds_duration_sum{task_name=~\"$task_name\",task_execution_id=~\"$task_execution_id\"}) by (task_name, task_execution_id)",
     "legendFormat": "{{task_name}}:{{task_execution_id}}"
    }
   ]
  },
  {
   "title": "Job Duration",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "sum(spring_batch_job_seconds_max{task_name=~\"$task_name\",name=~\"$job_name\"}) by (task_name,task_execution_id,name)",
     "legendFormat": "{{task_name}}:{{task_execution_id}}-{{name}}"
    }
   ]
  },
  {
   "title": "Task Rate",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "opm" }
   ],
   "targets": [
    {
     "expr": "rate(spring_cloud_task_seconds_count[1m])"
    }
   ]
  },
  {
   "title": "Active Task Rate",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "yaxes": [
    { "format": "opm" }
   ],
   "targets": [
    {
     "expr": "rate(spring_cloud_task_active_seconds_active_count{task_name=~\"$task_name\"}[1m]) ",
     "legendFormat": "{{task_name}}:{{task_execution_id}}"
    }
   ]
  },
  {
   "title": "Job Rate",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "rate(spring_batch_job_seconds_max{task_name=\"$task_name\",name=~\"$job_name\"}[1m])",
     "legendFormat": "{{task_name}}-{{name}}"
    }
   ]
  }
 ]
}