---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/source.toolkit.fluxcd.io/ocirepository_v1.json
apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: drm-exporter
spec:
  interval: 15m
  layerSelector:
    mediaType: application/vnd.cncf.helm.chart.content.v1.tar+gzip
    operation: copy
  ref:
    tag: 0.3.4
    digest: sha256:24cb7fff4a47fa8866c10b64ff2c465121f80992ec318f6bc08dc709f7c6d8ce
  url: oci://ghcr.io/home-operations/charts/drm-exporter
