---
# yaml-language-server: $schema=https://kubernetes-schemas.dmfrey.com/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: loki
spec:
  chartRef:
    kind: OCIRepository
    name: loki
  interval: 1h
  values:
    deploymentMode: SingleBinary

    loki:
      auth_enabled: false
      commonConfig:
        replication_factor: 1

      storage:
        type: s3
        s3:
          endpoint: http://garage.garage-system.svc.cluster.local:3900
          region: us-east-1
          bucketnames: loki
          s3ForcePathStyle: true
          insecure: true
        bucketNames:
          chunks: loki
          ruler: loki
          admin: loki

      schemaConfig:
        configs:
          - from: "2024-04-01"
            store: tsdb
            object_store: s3
            schema: v13
            index:
              prefix: loki_index_
              period: 24h

      limits_config:
        retention_period: 14d
        volume_enabled: true

      compactor:
        retention_enabled: true
        delete_request_store: s3

    singleBinary:
      replicas: 1
      persistence:
        storageClass: ceph-block
        size: 10Gi
      extraEnv:
        - name: AWS_ACCESS_KEY_ID
          valueFrom:
            secretKeyRef:
              name: loki-s3-secret
              key: S3_ACCESS_KEY
        - name: AWS_SECRET_ACCESS_KEY
          valueFrom:
            secretKeyRef:
              name: loki-s3-secret
              key: S3_SECRET_KEY

    chunksCache:
      enabled: false

    resultsCache:
      enabled: false

    lokiCanary:
      enabled: false

    test:
      enabled: false

    gateway:
      enabled: true
      replicas: 1

    backend:
      replicas: 0
    read:
      replicas: 0
    write:
      replicas: 0

    monitoring:
      serviceMonitor:
        enabled: true
      selfMonitoring:
        enabled: false
        grafanaAgent:
          installOperator: false
