---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/source.toolkit.fluxcd.io/ocirepository_v1.json
apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: loki
spec:
  interval: 15m
  layerSelector:
    mediaType: application/vnd.cncf.helm.chart.content.v1.tar+gzip
    operation: copy
  ref:
    tag: 18.13.4
    digest: sha256:d813dcf8b05ffb3c2f5e558a51489d8983782d0084b0217f3cfd9b919177b24a
  url: oci://ghcr.io/grafana-community/helm-charts/loki
