---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/source.toolkit.fluxcd.io/ocirepository_v1.json
apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: loki
spec:
  interval: 15m
  layerSelector:
    mediaType: application/vnd.cncf.helm.chart.content.v1.tar+gzip
    operation: copy
  ref:
    tag: 18.13.8
    digest: sha256:da2fa427007174d98229c9d71c14502a5a965f2e5396e6295cf799157bd4eb9f
  url: oci://ghcr.io/grafana-community/helm-charts/loki
