---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/source.toolkit.fluxcd.io/ocirepository_v1.json
apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: unifi-dns
spec:
  interval: 15m
  layerSelector:
    mediaType: application/vnd.cncf.helm.chart.content.v1.tar+gzip
    operation: copy
  ref:
    tag: 1.23.0
    digest: sha256:c7b8f2a30597547cde3008f2a1e3b5647a4ac0ea2dd3add0fffe2b84e0429aac
  url: oci://ghcr.io/home-operations/charts-mirror/external-dns
