---
# yaml-language-server: $schema=https://kubernetes-schemas.dmfrey.com/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: affine
spec:
  secretStoreRef:
    name: onepassword
    kind: ClusterSecretStore
  refreshInterval: 15m
  target:
    name: affine-secret
    template:
      engineVersion: v2
      data:
        AFFINE_ADMIN_EMAIL: "{{ .AFFINE_ADMIN_EMAIL }}"
        AFFINE_ADMIN_PASSWORD: "{{ .AFFINE_ADMIN_PASSWORD }}"
        config.json: |
          {
            "oauth": {
              "providers.oidc": {
                "clientId": "{{ .AUTHENTIK_CLIENT_ID }}",
                "clientSecret": "{{ .AUTHENTIK_CLIENT_SECRET }}",
                "issuer": "https://auth.dmfrey.com/application/o/affine/"
              }
            }
          }
  dataFrom:
  - extract:
      key: affine
