---
# yaml-language-server: $schema=https://kubernetes-schemas.dmfrey.com/dragonflydb.io/dragonfly_v1alpha1.json
apiVersion: dragonflydb.io/v1alpha1
kind: Dragonfly
metadata:
  name: authentik-dragonflydb
  annotations:
    secret.reloader.stakater.com/reload: authentik-dragonflydb-s3-secret

spec:

  replicas: 3
  enableReplicationReadinessGate: true

  image: ghcr.io/dragonflydb/dragonfly:v1.37.2@sha256:e45de310788d110d621655f6340b5b0818d860210ad6a350a4d277d57c14349a

  env:
    - name: MAX_MEMORY
      valueFrom:
        resourceFieldRef:
          resource: limits.memory
          divisor: 1Mi
    - name: AWS_ACCESS_KEY_ID
      valueFrom:
        secretKeyRef:
          name: authentik-dragonflydb-s3-secret
          key: AWS_ACCESS_KEY_ID
    - name: AWS_SECRET_ACCESS_KEY
      valueFrom:
        secretKeyRef:
          name: authentik-dragonflydb-s3-secret
          key: AWS_SECRET_ACCESS_KEY

  args:
    - --maxmemory=$(MAX_MEMORY)Mi
    - --proactor_threads=2
    - --cluster_mode=emulated
    - --lock_on_hashtags
    - --s3_endpoint=garage.garage-system.svc.cluster.local:3900
    - --s3_use_https=false

  snapshot:
    cron: 0 0 * * *
    dir: "s3://dragonflydb/authentik"

  resources:
    requests:
      cpu: 100m
    limits:
      memory: 512Mi
