---
# yaml-language-server: $schema=https://kubernetes-schemas.dmfrey.com/monitoring.coreos.com/probe_v1.json
kind: Probe
apiVersion: monitoring.coreos.com/v1
metadata:
  name: lan-icmp

spec:

  module: icmp

  prober:
    url: blackbox-exporter-lan.observability.svc.cluster.local:9115

  targets:
    staticConfig:
      static:
        - k8s-0.internal
        - k8s-1.internal
        - k8s-2.internal
        - nas.internal
        - ollama.internal

  metricRelabelings:
    - targetLabel: service
      replacement: blackbox-exporter-lan
      action: replace
---
# yaml-language-server: $schema=https://kubernetes-schemas.dmfrey.com/monitoring.coreos.com/probe_v1.json
apiVersion: monitoring.coreos.com/v1
kind: Probe
metadata:
  name: lan-nfs
spec:

  jobName: nfs_probe

  module: tcp_connect

  prober:
    url: blackbox-exporter-lan.observability.svc.cluster.local:9115

  targets:
    staticConfig:
      static:
        - nas.internal:2049

  metricRelabelings:
    - targetLabel: service
      replacement: blackbox-exporter-lan
      action: replace
---
# yaml-language-server: $schema=https://kubernetes-schemas.dmfrey.com/monitoring.coreos.com/probe_v1.json
apiVersion: monitoring.coreos.com/v1
kind: Probe
metadata:
  name: lan-zigbee-1
spec:

  jobName: zigbee_1_probe

  module: icmp

  prober:
    url: blackbox-exporter-lan.observability.svc.cluster.local:9115

  targets:
    staticConfig:
      static:
        - zigbee-1.internal

  metricRelabelings:
    - targetLabel: service
      replacement: blackbox-exporter-lan
      action: replace
---
# yaml-language-server: $schema=https://kubernetes-schemas.dmfrey.com/monitoring.coreos.com/probe_v1.json
apiVersion: monitoring.coreos.com/v1
kind: Probe
metadata:
  name: lan-zigbee-2
spec:

  jobName: zigbee_2_probe

  module: icmp

  prober:
    url: blackbox-exporter-lan.observability.svc.cluster.local:9115

  targets:
    staticConfig:
      static:
        - zigbee-2.internal

  metricRelabelings:
    - targetLabel: service
      replacement: blackbox-exporter-lan
      action: replace
