{
 "title": "Applications",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "stream_name", "label": "stream", "query": "label_values(stream_name)" },
   {
    "name": "application_name",
    "label": "application",
    "query": "label_values({stream_name=\"$stream_name\"},application_name)"
   },
   {
    "name": "name",
    "label": "name",
    "query": "label_values({stream_name=\"$stream_name\",application_name=~\"$application_name\"},name)"
   },
   {
    "name": "application_guid",
    "label": "guid",
    "query": "label_values({application_name=~\"$application_name\",stream_name=~\"$stream_name\"},application_guid)"
   }
  ]
 },
 "panels": [
  { "title": "System", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "# Apps",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 2, "x": 0, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "count(process_cpu_usage{stream_name=~\"$stream_name\",application_name=~\"$application_name\"})"
    }
   ]
  },
  {
   "title": "CPU",
   "type": "graph",
   "gridPos": { "h": 5, "w": 5, "x": 2, "y": 1 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "avg(process_cpu_usage{stream_name=~\"$stream_name\",application_name=~\"$application_name\"}) by (application_name,application_guid)",
     "legendFormat": "{{application_name}} [{{application_guid}}]"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "graph",
   "gridPos": { "h": 5, "w": 5, "x": 7, "y": 1 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "sum(jvm_memory_used_bytes{stream_name=~\"$stream_name\",application_name=~\"$application_name\"}) by (application_name,application_guid)",
     "legendFormat": "{{application_name}} [{{application_guid}}]"
    }
   ]
  },
  {
   "title": "Threads",
   "type": "graph",
   "gridPos": { "h": 5, "w": 4, "x": 12, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg(jvm_threads_live_threads{stream_name=~\"$stream_name\",application_name=~\"$application_name\"}) by (application_name,application_guid)",
     "legendFormat": "{{application_name}} [{{application_guid}}]"
    }
   ]
  },
  {
   "title": "Files",
   "type": "graph",
   "gridPos": { "h": 5, "w": 4, "x": 16, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg(process_files_open_files{stream_name=~\"$stream_name\",application_name=~\"$application_name\"}) by (application_name,application_guid)",
     "legendFormat": "{{application_name}} [{{application_guid}}]"
    }
   ]
  },
  {
   "title": "Classes",
   "type": "graph",
   "gridPos": { "h": 5, "w": 4, "x": 20, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg(jvm_classes_loaded_classes{stream_name=~\"$stream_name\",application_name=~\"$application_name\"}) by (application_name,application_guid)",
     "legendFormat": "{{application_name}} [{{application_guid}}]"
    }
   ]
  },
  { "title": "Applications", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 } },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 8, "x": 0, "y": 7 },
   "repeat": "application_name",
   "content": "<p style=\"text-align: center;font-size: 200%;color:#299c46;\" > $application_name </p>"
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 8, "x": 8, "y": 7 },
   "content": "<p style=\"text-align: center;font-size: 200%;color:#299c46;\" > $application_name </p>"
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 8, "x": 16, "y": 7 },
   "content": "<p style=\"text-align: center;font-size: 200%;color:#299c46;\" > $application_name </p>"
  },
  {
   "title": "Channel Throughput",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 9 },
   "repeat": "application_name",
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(spring_integration_send_seconds_count{type=\"channel\",name!=\"errorChannel\",name!=\"nullChannel\",result=\"success\",stream_name=~\"$stream_name\",application_name=~\"$application_name\",application_guid=~\"$application_guid\"}[60s])",
     "legendFormat": "{{name}} [{{application_guid}}]"
    }
   ]
  },
  {
   "title": "Channel Throughput",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(spring_integration_send_seconds_count{type=\"channel\",name!=\"errorChannel\",name!=\"nullChannel\",result=\"success\",stream_name=~\"$stream_name\",application_name=~\"$application_name\",application_guid=~\"$application_guid\"}[60s])",
     "legendFormat": "{{name}} [{{application_guid}}]"
    }
   ]
  },
  {
   "title": "Channel Throughput",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(spring_integration_send_seconds_count{type=\"channel\",name!=\"errorChannel\",name!=\"nullChannel\",result=\"success\",stream_name=~\"$stream_name\",application_name=~\"$application_name\",application_guid=~\"$application_guid\"}[60s])",
     "legendFormat": "{{name}} [{{application_guid}}]"
    }
   ]
  },
  {
   "title": "Channel Latency",
   "type": "graph",
   "description": "($application_name)",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 15 },
   "repeat": "application_name",
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "spring_integration_send_seconds_sum{type=\"channel\", stream_name=~\"$stream_name\",application_name=~\"$application_name\"}/spring_integration_send_seconds_count{type=\"channel\", stream_name=~\"$stream_name\",application_name=~\"$application_name\",application_guid=~\"$application_guid\"}",
     "legendFormat": "{{name}} [{{application_guid}}]"
    }
   ]
  },
  {
   "title": "Channel Latency",
   "type": "graph",
   "description": "($application_name)",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 15 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "spring_integration_send_seconds_sum{type=\"channel\", stream_name=~\"$stream_name\",application_name=~\"$application_name\"}/spring_integration_send_seconds_count{type=\"channel\", stream_name=~\"$stream_name\",application_name=~\"$application_name\",application_guid=~\"$application_guid\"}",
     "legendFormat": "{{name}} [{{application_guid}}]"
    }
   ]
  },
  {
   "title": "Channel Latency",
   "type": "graph",
   "description": "($application_name)",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 15 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "spring_integration_send_seconds_sum{type=\"channel\", stream_name=~\"$stream_name\",application_name=~\"$application_name\"}/spring_integration_send_seconds_count{type=\"channel\", stream_name=~\"$stream_name\",application_name=~\"$application_name\",application_guid=~\"$application_guid\"}",
     "legendFormat": "{{name}} [{{application_guid}}]"
    }
   ]
  },
  {
   "title": "Handler Throughput",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 21 },
   "repeat": "application_name",
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(spring_integration_send_seconds_count{type=\"handler\",result=\"success\",stream_name=~\"$stream_name\",application_name=~\"$application_name\",application_guid=~\"$application_guid\"}[60s])",
     "legendFormat": "{{name}} [{{application_guid}}]"
    }
   ]
  },
  {
   "title": "Handler Throughput",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 21 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(spring_integration_send_seconds_count{type=\"handler\",result=\"success\",stream_name=~\"$stream_name\",application_name=~\"$application_name\",application_guid=~\"$application_guid\"}[60s])",
     "legendFormat": "{{name}} [{{application_guid}}]"
    }
   ]
  },
  {
   "title": "Handler Throughput",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 21 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(spring_integration_send_seconds_count{type=\"handler\",result=\"success\",stream_name=~\"$stream_name\",application_name=~\"$application_name\",application_guid=~\"$application_guid\"}[60s])",
     "legendFormat": "{{name}} [{{application_guid}}]"
    }
   ]
  },
  {
   "title": "Message Source Rate",
   "type": "graph",
   "description": "($application_name)",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 27 },
   "repeat": "application_name",
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(spring_integration_receive_total{type=\"source\",result=\"success\",stream_name=~\"$stream_name\",application_name=~\"$application_name\",application_guid=~\"$application_guid\"}[60s])",
     "legendFormat": "{{name}} [{{application_guid}}]"
    }
   ]
  },
  {
   "title": "Message Source Rate",
   "type": "graph",
   "description": "($application_name)",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 27 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(spring_integration_receive_total{type=\"source\",result=\"success\",stream_name=~\"$stream_name\",application_name=~\"$application_name\",application_guid=~\"$application_guid\"}[60s])",
     "legendFormat": "{{name}} [{{application_guid}}]"
    }
   ]
  },
  {
   "title": "Message Source Rate",
   "type": "graph",
   "description": "($application_name)",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 27 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(spring_integration_receive_total{type=\"source\",result=\"success\",stream_name=~\"$stream_name\",application_name=~\"$application_name\",application_guid=~\"$application_guid\"}[60s])",
     "legendFormat": "{{name}} [{{application_guid}}]"
    }
   ]
  },
  {
   "title": "Channel  Failures",
   "type": "graph",
   "description": "($application_name)",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 33 },
   "repeat": "application_name",
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(spring_integration_send_seconds_count{type=\"channel\",result=\"failure\",stream_name=~\"$stream_name\",application_name=~\"$application_name\",application_guid=~\"$application_guid\"}[60s])",
     "legendFormat": "{{name}} [{{application_guid}}]"
    }
   ]
  },
  {
   "title": "Channel  Failures",
   "type": "graph",
   "description": "($application_name)",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 33 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(spring_integration_send_seconds_count{type=\"channel\",result=\"failure\",stream_name=~\"$stream_name\",application_name=~\"$application_name\",application_guid=~\"$application_guid\"}[60s])",
     "legendFormat": "{{name}} [{{application_guid}}]"
    }
   ]
  },
  {
   "title": "Channel  Failures",
   "type": "graph",
   "description": "($application_name)",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 33 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(spring_integration_send_seconds_count{type=\"channel\",result=\"failure\",stream_name=~\"$stream_name\",application_name=~\"$application_name\",application_guid=~\"$application_guid\"}[60s])",
     "legendFormat": "{{name}} [{{application_guid}}]"
    }
   ]
  },
  {
   "title": "Channels, Handlers, Sources Counts",
   "type": "graph",
   "description": "($application_name)",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 39 },
   "repeat": "application_name",
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "spring_integration_channels{stream_name=~\"$stream_name\", application_name=~\"$application_name\", application_guid=~\"$application_guid\"}",
     "legendFormat": "#channels [{{application_guid}}]"
    },
    {
     "expr": "spring_integration_handlers{stream_name=~\"$stream_name\", application_name=~\"$application_name\", application_guid=~\"$application_guid\"}",
     "legendFormat": "#handlers [{{application_guid}}]"
    },
    {
     "expr": "spring_integration_sources{stream_name=~\"$stream_name\", application_name=~\"$application_name\", application_guid=~\"$application_guid\"}",
     "legendFormat": "#sources [{{application_guid}}]"
    }
   ]
  },
  {
   "title": "Channels, Handlers, Sources Counts",
   "type": "graph",
   "description": "($application_name)",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 39 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "spring_integration_channels{stream_name=~\"$stream_name\", application_name=~\"$application_name\", application_guid=~\"$application_guid\"}",
     "legendFormat": "#channels [{{application_guid}}]"
    },
    {
     "expr": "spring_integration_handlers{stream_name=~\"$stream_name\", application_name=~\"$application_name\", application_guid=~\"$application_guid\"}",
     "legendFormat": "#handlers [{{application_guid}}]"
    },
    {
     "expr": "spring_integration_sources{stream_name=~\"$stream_name\", application_name=~\"$application_name\", application_guid=~\"$application_guid\"}",
     "legendFormat": "#sources [{{application_guid}}]"
    }
   ]
  },
  {
   "title": "Channels, Handlers, Sources Counts",
   "type": "graph",
   "description": "($application_name)",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 39 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "spring_integration_channels{stream_name=~\"$stream_name\", application_name=~\"$application_name\", application_guid=~\"$application_guid\"}",
     "legendFormat": "#channels [{{application_guid}}]"
    },
    {
     "expr": "spring_integration_handlers{stream_name=~\"$stream_name\", application_name=~\"$application_name\", application_guid=~\"$application_guid\"}",
     "legendFormat": "#handlers [{{application_guid}}]"
    },
    {
     "expr": "spring_integration_sources{stream_name=~\"$stream_name\", application_name=~\"$application_name\", application_guid=~\"$application_guid\"}",
     "legendFormat": "#sources [{{application_guid}}]"
    }
   ]
  }
 ]
}