{
 "title": "SCDF Kafka",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "stream_name", "label": "stream", "query": "label_values(stream_name)" },
   {
    "name": "application_name",
    "label": "application",
    "query": "label_values({stream_name=\"$stream_name\"},application_name)"
   },
   {
    "name": "application_guid",
    "label": "guid",
    "query": "label_values({application_name=~\"$application_name\",stream_name=~\"$stream_name\"},application_guid)"
   }
  ]
 },
 "panels": [
  { "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "type": "text",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 1 },
   "options": {
    "content": "This dashboard provides real-time visibility into **Spring Cloud Data Flow** Kafka streaming data pipelines. The data pipelines consist of Spring Cloud Stream, Spring Boot apps, built using the  Kafka message binder. For each streaming apps the dashboard could expose metrics [Kafka Producer](https://kafka.apache.org/documentation/#producer_monitoring), [Kafka Consumer](https://kafka.apache.org/documentation/#consumer_monitoring) and [Kafka Stream](https://docs.confluent.io/current/streams/monitoring.html). Use the drop-down menu on the top to filter based on, **Source**, **Stream**, **Application** and **Guid**.<br/>**NOTES:** Kafka Streams has metrics with two recording levels: `debug` and `info`. The `debug` level records all metrics, while the `info` level records only some of them. Use the `metrics.recording.level` configuration option to specify which metrics you want collected, see [Optional configuration parameters](https://docs.confluent.io/current/streams/developer-guide/config-streams.html#streams-developer-guide-optional-configs).<br/> Also this dashboard is applicable only for Spring Boot 2.3.+ and Micrometer 1.5.5 or newer streaming applications. "
   }
  },
  { "title": "Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 } },
  {
   "title": "Stream Applications",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "count(process_cpu_usage{stream_name=\"$stream_name\"})"
    }
   ]
  },
  {
   "title": "Logging Events",
   "type": "bargauge",
   "gridPos": { "h": 5, "w": 4, "x": 4, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "topK(10, sum(irate(logback_events_total{stream_name=\"$stream_name\",application_name=~\"$application_name\",application_guid=~\"$application_guid\"}[60s])) by (level))",
     "legendFormat": "{{level}}"
    }
   ]
  },
  {
   "title": "Top Records Lags",
   "type": "bargauge",
   "description": "- Number of messages consumer is behind producer on this partition.\n- Maximum number of messages consumer is behind producer, either for a specific partition or across all partitions on this client.\n\nRecords lag is the calculated difference between a consumer’s current log offset and a producer’s current log offset. Records lag max is the maximum observed value of records lag. The significance of these metrics’ values depends completely upon what your consumers are doing. If you have consumers that back up old messages to long-term storage, you would expect records lag to be significant. However, if your consumers are processing real-time data, consistently high lag values could be a sign of overloaded consumers, in which case both provisioning more consumers and splitting topics across more partitions could help increase throughput and reduce lag.",
   "gridPos": { "h": 5, "w": 4, "x": 8, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "topK(10, sum(irate(kafka_consumer_fetch_manager_records_lag_avg{stream_name=\"$stream_name\",application_name=~\"$application_name\",application_guid=~\"$application_guid\"}[60s])) by (application_name,application_guid))",
     "legendFormat": "MAX({{application_name}}-{{application_guid}})"
    }
   ]
  },
  {
   "title": "Top Produced Records Error Rate",
   "type": "bargauge",
   "description": "Average record sends per second that result in errors.",
   "gridPos": { "h": 5, "w": 4, "x": 12, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "topK(10, sum(kafka_producer_record_error_rate{stream_name=\"$stream_name\",application_name=~\"$application_name\",application_guid=~\"$application_guid\"}) by (application_name,application_guid,client_id))",
     "legendFormat": "{{application_name}}-{{application_guid}}-{{client_id}}"
    }
   ]
  },
  {
   "title": "Top Retry Rate",
   "type": "bargauge",
   "description": "Average number of re-tried record sends per-second ",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "topK(10, sum(irate(kafka_producer_record_retry_rate{stream_name=\"$stream_name\",application_name=~\"$application_name\",application_guid=~\"$application_guid\"}[60s])) by (application_name,application_guid,client_id))",
     "legendFormat": "{{application_name}}-{{application_guid}}-{{client_id}}"
    }
   ]
  },
  { "title": "Kafka Records", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 11 } },
  {
   "title": "Produced Records Rate",
   "type": "graph",
   "description": "The average number of records sent per second for a topic.",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "kafka_producer_record_send_rate{stream_name=~\"$stream_name\",application_name=~\"$application_name\",application_guid=~\"$application_guid\"}",
     "legendFormat": "{{application_name}}-{{application_guid}}-{{client_id}}"
    }
   ]
  },
  {
   "title": "Consumed Records Rate",
   "type": "graph",
   "description": "Average number of records consumed per second for a specific topic or across all topics.\n\nEach Kafka message is a single data record. The rate of records consumed per second may not strongly correlate with the rate of bytes consumed because messages can be of variable size. Depending on your producers and workload, in typical deployments you should expect this number to remain fairly constant. By monitoring this metric over time, you can discover trends in your data consumption and create a baseline against which you can alert.",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "kafka_consumer_fetch_manager_records_consumed_rate{stream_name=~\"$stream_name\",application_name=~\"$application_name\",application_guid=~\"$application_guid\",client_id!~\".*-restore-consumer\"}",
     "legendFormat": "{{application_name}}-{{application_guid}}-{{client_id}}"
    }
   ]
  },
  {
   "title": "Send Record Size",
   "type": "graph",
   "description": "Average size of the records sent per second for a topic.",
   "gridPos": { "h": 9, "w": 4, "x": 16, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "kafka_producer_record_size_avg{stream_name=\"$stream_name\",application_name=~\"$application_name\",application_guid=~\"$application_guid\",client_id!~\".*-restore-consumer\"}",
     "legendFormat": "AVG({{application_name}}-{{application_guid}})"
    },
    {
     "expr": "kafka_producer_record_size_max{stream_name=\"$stream_name\",application_name=~\"$application_name\",application_guid=~\"$application_guid\",client_id!~\".*-restore-consumer\"}",
     "legendFormat": "MAX({{application_name}}-{{application_guid}})"
    }
   ]
  },
  {
   "title": "Record Queue Time",
   "type": "graph",
   "description": "This attribute displays the average time in milliseconds record batches spent in the record accumulator.",
   "gridPos": { "h": 9, "w": 4, "x": 20, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "kafka_producer_record_queue_time_avg{stream_name=\"$stream_name\",application_name=~\"$application_name\",application_guid=~\"$application_guid\",client_id!~\".*-restore-consumer\"}",
     "legendFormat": "AVG({{application_name}}-{{application_guid}})"
    }
   ]
  },
  {
   "title": "Produced Records Error Rate",
   "type": "graph",
   "description": "Average record sends per second that result in errors.",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "kafka_producer_record_error_rate{stream_name=\"$stream_name\",application_name=~\"$application_name\",application_guid=~\"$application_guid\"}",
     "legendFormat": "{{application_name}}-{{application_guid}}-{{client_id}}"
    }
   ]
  },
  {
   "title": "Produced Records Retry Rate",
   "type": "graph",
   "description": "Average number of re-tried record sends per-second ",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "kafka_producer_record_retry_rate{stream_name=~\"$stream_name\",application_name=~\"$application_name\",application_guid=~\"$application_guid\"}",
     "legendFormat": "{{application_name}}-{{application_guid}}-{{client_id}}"
    }
   ]
  },
  {
   "title": "Consumed Records Lag",
   "type": "graph",
   "description": "- Number of messages consumer is behind producer on this partition.\n- Maximum number of messages consumer is behind producer, either for a specific partition or across all partitions on this client.\n\nRecords lag is the calculated difference between a consumer’s current log offset and a producer’s current log offset. Records lag max is the maximum observed value of records lag. The significance of these metrics’ values depends completely upon what your consumers are doing. If you have consumers that back up old messages to long-term storage, you would expect records lag to be significant. However, if your consumers are processing real-time data, consistently high lag values could be a sign of overloaded consumers, in which case both provisioning more consumers and splitting topics across more partitions could help increase throughput and reduce lag.",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 21 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "kafka_consumer_fetch_manager_records_lag_avg{stream_name=~\"$stream_name\",application_name=~\"$application_name\",application_guid=~\"$application_guid\",client_id!~\".*-restore-consumer\"}",
     "legendFormat": "AVG({{application_name}}-{{application_guid}})"
    },
    {
     "expr": "kafka_consumer_fetch_manager_records_lag_max{stream_name=~\"$stream_name\",application_name=~\"$application_name\",application_guid=~\"$application_guid\",client_id!~\".*-restore-consumer\"}",
     "legendFormat": "MAX({{application_name}}-{{application_guid}})"
    }
   ]
  },
  { "title": "Kafka Producer", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 30 } },
  {
   "title": "Request Rate",
   "type": "graph",
   "description": "The average number of requests sent per second to the broker.",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "kafka_producer_request_rate{stream_name=~\"$stream_name\",application_name=~\"$application_name\",application_guid=~\"$application_guid\"}",
     "legendFormat": "{{application_name}}-{{application_guid}}-{{client_id}}"
    }
   ]
  },
  {
   "title": "Response Rate",
   "type": "graph",
   "description": "The average number of responses received per second.",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "kafka_producer_response_rate{stream_name=~\"$stream_name\",application_name=~\"$application_name\",application_guid=~\"$application_guid\"}",
     "legendFormat": "{{application_name}}-{{application_guid}}-{{client_id}}"
    }
   ]
  },
  {
   "title": "Request Latency",
   "type": "graph",
   "description": "The average request latency in ms.\nThe average request latency is a measure of the amount of time between when KafkaProducer.send() was called until the producer receives a response from the broker.",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "kafka_producer_request_latency_avg{stream_name=~\"$stream_name\",application_name=~\"$application_name\",application_guid=~\"$application_guid\"}",
     "legendFormat": "AVG({{application_name}}-{{application_guid}}-{{client_id}})"
    },
    {
     "expr": "kafka_producer_request_latency_max{stream_name=~\"$stream_name\",application_name=~\"$application_name\",application_guid=~\"$application_guid\"}",
     "legendFormat": "MAX({{application_name}}-{{application_guid}}-{{client_id}})"
    }
   ]
  },
  {
   "title": "Thread IO Wait Time",
   "type": "graph",
   "description": "The average length of time the I/O thread spent waiting for a socket ready for reads or writes in nanoseconds.",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "yaxes": [
    { "format": "ns" }
   ],
   "targets": [
    {
     "expr": "kafka_producer_io_wait_time_ns_avg{stream_name=~\"$stream_name\",application_name=~\"$application_name\",application_guid=~\"$application_guid\"}",
     "legendFormat": "{{application_name}}-{{application_guid}}-{{client_id}}"
    }
   ]
  },
  {
   "title": "Thread IO Wait Ratio",
   "type": "graph",
   "description": "The fraction of time the I/O thread spent waiting.\n\npercentage of time the CPU is idle and there is at least one I/O operation in progress.",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "kafka_producer_io_wait_ratio{stream_name=~\"$stream_name\",application_name=~\"$application_name\",application_guid=~\"$application_guid\"}",
     "legendFormat": "{{application_name}}-{{application_guid}}-{{client_id}}"
    }
   ]
  },
  {
   "title": "Network IO Rate",
   "type": "graph",
   "description": "average number per second of network operations, reads or writes, on all connections.",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "kafka_producer_network_io_rate{stream_name=~\"$stream_name\",application_name=~\"$application_name\",application_guid=~\"$application_guid\"}",
     "legendFormat": "{{application_name}}-{{application_guid}}-{{client_id}}"
    }
   ]
  },
  {
   "title": "Compression Rate",
   "type": "graph",
   "description": "This metric reflects the ratio of data compression in the batches of data the producer sends to the broker. A higher compression rate indicates greater efficiency. If this metric drops, it could indicate that there’s a problem with the shape of data or that a rogue producer is sending uncompressed data.",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 49 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "kafka_producer_compression_rate_avg{stream_name=~\"$stream_name\",application_name=~\"$application_name\",application_guid=~\"$application_guid\"}",
     "legendFormat": "{{application_name}}-{{application_guid}}-{{client_id}}"
    }
   ]
  },
  {
   "title": "Batch Size",
   "type": "graph",
   "description": "Average number of bytes sent per partition per request (e.g. data size send to different partition on the topic). \nIndicates partition skewness, partition throughput etc. Helps for partition strategy optimizations.",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 49 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "kafka_producer_batch_size_avg{stream_name=~\"$stream_name\",application_name=~\"$application_name\",application_guid=~\"$application_guid\"}",
     "legendFormat": "{{application_name}}-{{application_guid}}-{{client_id}}"
    }
   ]
  },
  {
   "title": "records_per_request_avg",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 49 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "kafka_producer_records_per_request_avg{stream_name=~\"$stream_name\",application_name=~\"$application_name\",application_guid=~\"$application_guid\"}",
     "legendFormat": "{{application_name}}-{{application_guid}}-{{client_id}}"
    }
   ]
  },
  {
   "title": "Outgoing Byte Rate",
   "type": "graph",
   "description": "The average number of outgoing bytes sent per second to all servers.\nThe producer network throughput. ",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 58 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "kafka_producer_outgoing_byte_rate{stream_name=~\"$stream_name\",application_name=~\"$application_name\",application_guid=~\"$application_guid\"}",
     "legendFormat": "{{application_name}}-{{application_guid}}-{{client_id}}"
    }
   ]
  },
  {
   "title": "Requests in Flight",
   "type": "graph",
   "description": "Current number of outstanding requests awaiting a response.",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 58 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "kafka_producer_requests_in_flight{stream_name=~\"$stream_name\",application_name=~\"$application_name\",application_guid=~\"$application_guid\"}",
     "legendFormat": "{{application_name}}-{{application_guid}}-{{client_id}}"
    }
   ]
  },
  {
   "title": "Waiting Threads",
   "type": "graph",
   "description": "Number of user threads blocked waiting for buffer memory to enqueue their records",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 58 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "kafka_producer_waiting_threads{stream_name=~\"$stream_name\",application_name=~\"$application_name\",application_guid=~\"$application_guid\"}",
     "legendFormat": "{{application_name}}-{{application_guid}}-{{client_id}}"
    }
   ]
  },
  { "title": "Kafka Consumer", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 67 } },
  {
   "title": "Fetch Rate",
   "type": "graph",
   "description": "Number of fetch requests per second from the consumer.\n\nThe fetch rate of a consumer can be a good indicator of overall consumer health. A minimum fetch rate approaching a value of zero could potentially signal an issue on the consumer. In a healthy consumer, the minimum fetch rate will usually be non-zero, so if you see this value dropping, it could be a sign of consumer failure.\n\n",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 68 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "kafka_consumer_fetch_manager_fetch_rate{stream_name=~\"$stream_name\",application_name=~\"$application_name\",application_guid=~\"$application_guid\",client_id!~\".*-restore-consumer\"}",
     "legendFormat": "{{application_name}}-{{application_guid}}"
    }
   ]
  },
  {
   "title": "Fetch Latency",
   "type": "graph",
   "description": "Maximum and Average time taken for any fetch request.",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 68 },
   "fieldConfig": { "defaults": { "unit": "dtdurationms" } },
   "yaxes": [
    { "format": "dtdurationms" }
   ],
   "targets": [
    {
     "expr": "kafka_consumer_fetch_manager_fetch_latency_avg{stream_name=~\"$stream_name\",application_name=~\"$application_name\",application_guid=~\"$application_guid\",client_id!~\".*-restore-consumer\"}",
     "legendFormat": "AVG({{application_name}}-{{application_guid}})"
    },
    {
     "expr": "kafka_consumer_fetch_manager_fetch_latency_max{stream_name=~\"$stream_name\",application_name=~\"$application_name\",application_guid=~\"$application_guid\",client_id!~\".*-restore-consumer\"}",
     "legendFormat": "MAX({{application_name}}-{{application_guid}})"
    }
   ]
  },
  {
   "title": "Bytes Consumed Rate",
   "type": "graph",
   "description": "Average number of bytes consumed per second for a specific topic or across all topics.\n\nConsumer network throughput. A sudden drop in the rate of records consumed (records-consumed-rate) could indicate a failing consumer, but if its network throughput (bytes-consumed-rate) remains constant, it’s still healthy—just consuming fewer, larger-sized messages. Observing traffic volume over time, in the context of other metrics, is important for diagnosing anomalous network usage.\n\n",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 68 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "kafka_consumer_fetch_manager_bytes_consumed_rate{stream_name=~\"$stream_name\",application_name=~\"$application_name\",application_guid=~\"$application_guid\",client_id!~\".*-restore-consumer\"}",
     "legendFormat": "{{application_name}}-{{application_guid}}"
    }
   ]
  },
  { "title": "Kafka Stream Thread", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 77 } },
  {
   "title": "Thread Operation Rate",
   "type": "graph",
   "description": "The average number of respective operations per second across all tasks.\n\nThe fetch rate of a consumer can be a good indicator of overall consumer health. A minimum fetch rate approaching a value of zero could potentially signal an issue on the consumer. In a healthy consumer, the minimum fetch rate will usually be non-zero, so if you see this value dropping, it could be a sign of consumer failure.\n\n",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 78 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "kafka_stream_thread_commit_rate{stream_name=~\"$stream_name\",application_name=~\"$application_name\",application_guid=~\"$application_guid\",client_id!~\".*-restore-consumer\"}",
     "legendFormat": "Commit: {{application_name}}-{{application_guid}}"
    },
    {
     "expr": "kafka_stream_thread_poll_rate{stream_name=~\"$stream_name\",application_name=~\"$application_name\",application_guid=~\"$application_guid\",client_id!~\".*-restore-consumer\"}",
     "legendFormat": "Poll: {{application_name}}-{{application_guid}}"
    },
    {
     "expr": "kafka_stream_thread_process_rate{stream_name=~\"$stream_name\",application_name=~\"$application_name\",application_guid=~\"$application_guid\",client_id!~\".*-restore-consumer\"}",
     "legendFormat": "Process: {{application_name}}-{{application_guid}}"
    },
    {
     "expr": "kafka_stream_thread_punctuate_rate{stream_name=~\"$stream_name\",application_name=~\"$application_name\",application_guid=~\"$application_guid\",client_id!~\".*-restore-consumer\"}",
     "legendFormat": "Punctuate: {{application_name}}-{{application_guid}}"
    }
   ]
  },
  {
   "title": "Thread Operation Latency",
   "type": "graph",
   "description": "The average execution time in ms, for the respective operation, across all running tasks of this thread.",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 78 },
   "fieldConfig": { "defaults": { "unit": "dtdurationms" } },
   "yaxes": [
    { "format": "dtdurationms" }
   ],
   "targets": [
    {
     "expr": "kafka_stream_thread_commit_latency_avg{stream_name=~\"$stream_name\",application_name=~\"$application_name\",application_guid=~\"$application_guid\",client_id!~\".*-restore-consumer\"}",
     "legendFormat": "avg({{application_name}}-{{application_guid}})"
    },
    {
     "expr": "kafka_stream_thread_poll_latency_avg{stream_name=~\"$stream_name\",application_name=~\"$application_name\",application_guid=~\"$application_guid\",client_id!~\".*-restore-consumer\"}",
     "legendFormat": "poll({{application_name}}-{{application_guid}})"
    },
    {
     "expr": "kafka_stream_thread_process_latency_avg{stream_name=~\"$stream_name\",application_name=~\"$application_name\",application_guid=~\"$application_guid\",client_id!~\".*-restore-consumer\"}",
     "legendFormat": "process({{application_name}}-{{application_guid}})"
    },
    {
     "expr": "kafka_stream_thread_punctuate_latency_avg{stream_name=~\"$stream_name\",application_name=~\"$application_name\",application_guid=~\"$application_guid\",client_id!~\".*-restore-consumer\"}",
     "legendFormat": "punctuate({{application_name}}-{{application_guid}})"
    }
   ]
  },
  {
   "title": "Thread Task Created & Closed Rate",
   "type": "graph",
   "description": "The average number of tasks created and closed per second.\n\nThe fetch rate of a consumer can be a good indicator of overall consumer health. A minimum fetch rate approaching a value of zero could potentially signal an issue on the consumer. In a healthy consumer, the minimum fetch rate will usually be non-zero, so if you see this value dropping, it could be a sign of consumer failure.\n\n",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 78 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "kafka_stream_thread_task_created_rate{stream_name=~\"$stream_name\",application_name=~\"$application_name\",application_guid=~\"$application_guid\",client_id!~\".*-restore-consumer\"}",
     "legendFormat": "Created: {{application_name}}-{{application_guid}}"
    },
    {
     "expr": "kafka_stream_thread_task_closed_rate{stream_name=~\"$stream_name\",application_name=~\"$application_name\",application_guid=~\"$application_guid\",client_id!~\".*-restore-consumer\"}",
     "legendFormat": "Closed: {{application_name}}-{{application_guid}}"
    }
   ]
  },
  {
   "title": "Kafka Stream Task & Process Node",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 87 }
  },
  {
   "type": "text",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 88 },
   "options": {
    "content": "The metrics is only availale if the recording level (e.g. `metrics.recording.level` configuration option) is set to `debug`."
   }
  },
  {
   "title": "Node Process",
   "type": "stat",
   "description": "The total number of records processed by a source node.",
   "gridPos": { "h": 5, "w": 4, "x": 8, "y": 88 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "rate(kafka_stream_processor_node_process_total{stream_name=~\"$stream_name\",application_name=~\"$application_name\",application_guid=~\"$application_guid\",client_id!~\".*-restore-consumer\"}[60s])",
     "legendFormat": "TaskID: {{task_id}}"
    }
   ]
  },
  {
   "title": "Task Dropped Records",
   "type": "stat",
   "description": "The total number of records dropped within this task.",
   "gridPos": { "h": 5, "w": 4, "x": 12, "y": 88 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "rate(kafka_stream_task_dropped_records_total{stream_name=~\"$stream_name\",application_name=~\"$application_name\",application_guid=~\"$application_guid\",client_id!~\".*-restore-consumer\"}[60s])",
     "legendFormat": "TaskID: {{task_id}}"
    }
   ]
  },
  {
   "title": "Enforced Processing",
   "type": "stat",
   "description": "The total number of enforced processing for this task.",
   "gridPos": { "h": 5, "w": 4, "x": 16, "y": 88 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "rate(kafka_stream_task_enforced_processing_total{stream_name=~\"$stream_name\",application_name=~\"$application_name\",application_guid=~\"$application_guid\",client_id!~\".*-restore-consumer\"}[60s])",
     "legendFormat": "TaskID: {{task_id}}"
    }
   ]
  },
  {
   "title": "Task Commit vs Process Ratio",
   "type": "stat",
   "description": "Ratio between the total number of commit and process operations for this task.",
   "gridPos": { "h": 5, "w": 4, "x": 20, "y": 88 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "rate(kafka_stream_task_commit_total{stream_name=~\"$stream_name\",application_name=~\"$application_name\",application_guid=~\"$application_guid\",client_id!~\".*-restore-consumer\"}[60s])",
     "legendFormat": "TaskID: {{task_id}}"
    }
   ]
  },
  {
   "title": "Task Rate",
   "type": "graph",
   "description": "The average number of respective operations per second across all tasks.\n\nThe fetch rate of a consumer can be a good indicator of overall consumer health. A minimum fetch rate approaching a value of zero could potentially signal an issue on the consumer. In a healthy consumer, the minimum fetch rate will usually be non-zero, so if you see this value dropping, it could be a sign of consumer failure.\n\n",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 93 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "kafka_stream_task_commit_rate{stream_name=~\"$stream_name\",application_name=~\"$application_name\",application_guid=~\"$application_guid\",client_id!~\".*-restore-consumer\"}",
     "legendFormat": "Commit: {{application_name}}-{{application_guid}}-{{task_id}}"
    },
    {
     "expr": "kafka_stream_task_process_rate{stream_name=~\"$stream_name\",application_name=~\"$application_name\",application_guid=~\"$application_guid\",client_id!~\".*-restore-consumer\"}",
     "legendFormat": "Process: {{application_name}}-{{application_guid}}-{{task_id}}"
    }
   ]
  },
  {
   "title": "Task Latency",
   "type": "graph",
   "description": "The average execution time in ns, for the respective operation for this task.",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 93 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "yaxes": [
    { "format": "ns" }
   ],
   "targets": [
    {
     "expr": "kafka_stream_task_commit_latency_avg{stream_name=~\"$stream_name\",application_name=~\"$application_name\",application_guid=~\"$application_guid\",client_id!~\".*-restore-consumer\"}",
     "legendFormat": "commit({{application_name}}-{{application_guid}}--{{task_id}})"
    },
    {
     "expr": "kafka_stream_task_process_latency_avg{stream_name=~\"$stream_name\",application_name=~\"$application_name\",application_guid=~\"$application_guid\",client_id!~\".*-restore-consumer\"}",
     "legendFormat": "process({{application_name}}-{{application_guid}}--{{task_id}})"
    }
   ]
  },
  {
   "title": "Record Lateness",
   "type": "graph",
   "description": "The [average | maximum] observed lateness (stream time - record timestamp) for this task. For more information on late records, see Out-of-Order Handling.",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 93 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "yaxes": [
    { "format": "ns" }
   ],
   "targets": [
    {
     "expr": "kafka_stream_task_record_lateness_avg{stream_name=~\"$stream_name\",application_name=~\"$application_name\",application_guid=~\"$application_guid\",client_id!~\".*-restore-consumer\"}",
     "legendFormat": "avg({{application_name}}-{{application_guid}}--{{task_id}})"
    },
    {
     "expr": "kafka_stream_task_record_lateness_max{stream_name=~\"$stream_name\",application_name=~\"$application_name\",application_guid=~\"$application_guid\",client_id!~\".*-restore-consumer\"}",
     "legendFormat": "max({{application_name}}-{{application_guid}}--{{task_id}})"
    }
   ]
  },
  {
   "title": "Enforced Processing Rate",
   "type": "graph",
   "description": "The average number of enforced processing per second for this task.\n\nThe fetch rate of a consumer can be a good indicator of overall consumer health. A minimum fetch rate approaching a value of zero could potentially signal an issue on the consumer. In a healthy consumer, the minimum fetch rate will usually be non-zero, so if you see this value dropping, it could be a sign of consumer failure.\n\n",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 102 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "kafka_stream_task_enforced_processing_rate{stream_name=~\"$stream_name\",application_name=~\"$application_name\",application_guid=~\"$application_guid\",client_id!~\".*-restore-consumer\"}",
     "legendFormat": " {{application_name}}-{{application_guid}}-{{task_id}}"
    }
   ]
  },
  {
   "title": "Processor Node Process Rate",
   "type": "graph",
   "description": "The average number of records processed per second by a source node.\n\nThe fetch rate of a consumer can be a good indicator of overall consumer health. A minimum fetch rate approaching a value of zero could potentially signal an issue on the consumer. In a healthy consumer, the minimum fetch rate will usually be non-zero, so if you see this value dropping, it could be a sign of consumer failure.\n\n",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 102 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "kafka_stream_processor_node_process_rate{stream_name=~\"$stream_name\",application_name=~\"$application_name\",application_guid=~\"$application_guid\",client_id!~\".*-restore-consumer\"}",
     "legendFormat": " {{application_name}}-{{application_guid}}-{{task_id}}"
    }
   ]
  },
  {
   "title": "Dropped Records Rate",
   "type": "graph",
   "description": "The average number of records dropped within this task.\n\nThe fetch rate of a consumer can be a good indicator of overall consumer health. A minimum fetch rate approaching a value of zero could potentially signal an issue on the consumer. In a healthy consumer, the minimum fetch rate will usually be non-zero, so if you see this value dropping, it could be a sign of consumer failure.\n\n",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 102 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "kafka_stream_task_dropped_records_rate{stream_name=~\"$stream_name\",application_name=~\"$application_name\",application_guid=~\"$application_guid\",client_id!~\".*-restore-consumer\"}",
     "legendFormat": "{{application_name}}-{{application_guid}}-{{task_id}}"
    }
   ]
  }
 ]
}