{
 "title": "Streams",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "stream_name", "label": "Stream", "query": "label_values(stream_name)" }
  ]
 },
 "panels": [
  {
   "title": "Total Stream Count",
   "type": "singlestat",
   "description": "Number of  deployed Streams",
   "gridPos": { "h": 4, "w": 2, "x": 0, "y": 0 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "count(count by (stream_name) (spring_integration_send_seconds_count))"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 2, "x": 2, "y": 0 },
   "format": "decbytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(jvm_memory_used_bytes{stream_name=~\"$stream_name\"})"
    }
   ]
  },
  {
   "title": "Error Channel",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 2, "x": 4, "y": 0 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(spring_integration_send_seconds_count{type=\"channel\",name=\"errorChannel\",stream_name=~\"$stream_name\"})"
    }
   ]
  },
  {
   "title": "Number of Apps",
   "type": "graph",
   "description": "Average throughput of the apps in the stream",
   "gridPos": { "h": 8, "w": 3, "x": 6, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "count(system_cpu_usage{stream_name=~\"$stream_name\"}) by (stream_name)",
     "legendFormat": "{{stream_name}} "
    }
   ]
  },
  {
   "title": "Stream Throughput",
   "type": "graph",
   "description": "Average throughput of the apps in the stream",
   "gridPos": { "h": 8, "w": 5, "x": 9, "y": 0 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "avg(rate(spring_integration_send_seconds_count{result=\"success\", application_type=\"source\", stream_name=~\"$stream_name\"}[60s])) by (stream_name,result)",
     "legendFormat": "{{stream_name}} -input"
    },
    {
     "expr": "avg(rate(spring_integration_send_seconds_count{result=\"success\", application_type=\"sink\", stream_name=~\"$stream_name\"}[60s])) by (stream_name,result)",
     "legendFormat": "{{stream_name}} -output"
    },
    {
     "expr": "avg(rate(spring_integration_send_seconds_count{result=\"failure\", stream_name=~\"$stream_name\"}[60s])) by (stream_name,result)",
     "legendFormat": "{{stream_name}}  ({{result}})"
    }
   ]
  },
  {
   "title": "Stream Latency",
   "type": "graph",
   "description": "Average latency of all apps in a stream",
   "gridPos": { "h": 8, "w": 5, "x": 14, "y": 0 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "sum(spring_integration_send_seconds_sum{result=\"success\",stream_name=~\"$stream_name\"}/spring_integration_send_seconds_count{result=\"success\",stream_name=~\"$stream_name\"}) by (stream_name,result)",
     "legendFormat": "{{stream_name}}"
    },
    {
     "expr": "sum(spring_integration_send_seconds_sum{result=\"failure\",stream_name=~\"$stream_name\"}/spring_integration_send_seconds_count{result=\"success\",stream_name=~\"$stream_name\"}) by (stream_name,result)",
     "legendFormat": "{{stream_name}}  ({{result}})"
    }
   ]
  },
  {
   "title": "Message Source Rate",
   "type": "graph",
   "gridPos": { "h": 8, "w": 5, "x": 19, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(spring_integration_receive_total{result=\"success\", stream_name=~\"$stream_name\"}[60s])",
     "legendFormat": "{{stream_name}}  "
    },
    {
     "expr": "rate(spring_integration_receive_total{result=\"failure\", stream_name=~\"$stream_name\"}[60s])",
     "legendFormat": "{{stream_name}} - ({{result}})"
    }
   ]
  },
  {
   "title": "Total App Count",
   "type": "singlestat",
   "description": "Number of active Application Instances",
   "gridPos": { "h": 4, "w": 2, "x": 0, "y": 4 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "count(count by (application_guid) (spring_integration_send_seconds_count))"
    }
   ]
  },
  {
   "title": "CPU",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 2, "x": 2, "y": 4 },
   "format": "percentunit",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(process_cpu_usage{stream_name=~\"$stream_name\"})"
    }
   ]
  },
  {
   "title": "Tomcat Errors",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 2, "x": 4, "y": 4 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(tomcat_global_error_total{stream_name=~\"$stream_name\"})"
    }
   ]
  },
  {
   "title": "Stream CPU",
   "type": "graph",
   "gridPos": { "h": 6, "w": 5, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "sum(process_cpu_usage{stream_name=~\"$stream_name\"}) by (stream_name)",
     "legendFormat": "{{stream_name}}"
    }
   ]
  },
  {
   "title": "Stream Memory",
   "type": "graph",
   "gridPos": { "h": 6, "w": 5, "x": 5, "y": 8 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "sum(jvm_memory_used_bytes{stream_name=~\"$stream_name\"}) by (stream_name)",
     "legendFormat": "{{stream_name}}"
    }
   ]
  },
  {
   "title": "Stream Open Files",
   "type": "graph",
   "gridPos": { "h": 6, "w": 5, "x": 10, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(process_files_open_files{stream_name=~\"$stream_name\"}) by (stream_name)",
     "legendFormat": "{{stream_name}}"
    }
   ]
  },
  {
   "title": "Stream Threads",
   "type": "graph",
   "gridPos": { "h": 6, "w": 5, "x": 15, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(jvm_threads_live_threads{stream_name=~\"$stream_name\"}) by (stream_name)",
     "legendFormat": "{{stream_name}}"
    }
   ]
  },
  {
   "title": "Error Channel Throughput",
   "type": "graph",
   "gridPos": { "h": 6, "w": 4, "x": 20, "y": 8 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "sum(rate(spring_integration_send_seconds_count{type=\"channel\",name=\"errorChannel\",stream_name=~\"$stream_name\"}[60s])) by (stream_name)",
     "legendFormat": "{{stream_name}}"
    }
   ]
  }
 ]
}