---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app node-red
spec:
  chartRef:
    kind: OCIRepository
    name: node-red

  interval: 1h

  values:
    controllers:
      node-red:
        type: statefulset

        containers:
          node-red:
            image:
              repository: nodered/node-red
              tag: 4.1.7-18-minimal@sha256:a1951e845a7e0b617b21bac40ce43a29f977cb099f3151df97b956b26da3f747

            env:
              TZ: America/New_York
              FLOWS: "flows.json"
              NODE_RED_ENABLE_PROJECTS: "true"
              NODE_RED_ENABLE_SAFE_MODE: "false"

            resources:
              requests:
                cpu: 10m
              limits:
                memory: 350Mi

    defaultPodOptions:
      terminationGracePeriodSeconds: 10
      securityContext:
        runAsUser: 1000
        runAsGroup: 1000
        runAsNonRoot: true
        fsGroup: 1000
        fsGroupChangePolicy: "OnRootMismatch"

    service:
      node-red:
        controller: *app
        ports:
          http:
            port: &port 1880

    route:
      node-red:
        hostnames:
          - "{{ .Release.Name }}.dmfrey.com"
        annotations:
          gethomepage.dev/enabled: "true"
          gethomepage.dev/group: Home
          gethomepage.dev/name: Node-RED
          gethomepage.dev/icon: node-red.png
          gethomepage.dev/description: Low-code programming for event-driven applications
        parentRefs:
          - name: envoy-internal
            namespace: network
            sectionName: https
        rules:
          - backendRefs:
              - name: *app
                port: *port

    persistence:
      data:
        existingClaim: "{{ .Release.Name }}"

      tmp:
        type: emptyDir
        medium: Memory
