---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: plex
spec:
  accessModes:
    - ReadWriteOnce
  dataSourceRef:
    apiGroup: volsync.backube
    kind: ReplicationDestination
    name: plex-bootstrap
  resources:
    requests:
      storage: 35Gi
  storageClassName: ceph-block
