---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ./helmrelease.yaml
  - ./ocirepository.yaml

configMapGenerator:
  - name: nginx-config
    files:
      - default.conf=./resources/nginx-default.conf
    options:
      labels:
        kustomize.toolkit.fluxcd.io/substitute: disabled
  - name: index-html
    files:
      - index.html=./resources/index.html
    options:
      labels:
        kustomize.toolkit.fluxcd.io/substitute: disabled
  - name: bedroom-suite-viewer-html
    files:
      - bedroom-suite-viewer.html=./resources/bedroom-suite-viewer-v2.html
    options:
      labels:
        kustomize.toolkit.fluxcd.io/substitute: disabled
  - name: bedroom-suite-sheet-layout-html
    files:
      - bedroom-suite-sheet-layout.html=./resources/bedroom-suite-sheet-layout-v4.html
    options:
      labels:
        kustomize.toolkit.fluxcd.io/substitute: disabled

generatorOptions:
  disableNameSuffixHash: true
  annotations:
    kustomize.toolkit.fluxcd.io/substitute: disabled
