---
# yaml-language-server: $schema=https://kubernetes-schemas.dmfrey.com/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: tempo
spec:
  chartRef:
    kind: OCIRepository
    name: tempo
  interval: 1h
  values:
    tempo:
      storage:
        trace:
          backend: s3
          s3:
            bucket: tempo
            endpoint: garage.garage-system.svc.cluster.local:3900
            forcepathstyle: true
            insecure: true
            region: us-east-1
      metricsGenerator:
        enabled: true
        remoteWriteUrl: http://prometheus-operated.observability.svc.cluster.local:9090/api/v1/write

    extraEnv:
      - name: AWS_ACCESS_KEY_ID
        valueFrom:
          secretKeyRef:
            name: tempo-s3-secret
            key: S3_ACCESS_KEY
      - name: AWS_SECRET_ACCESS_KEY
        valueFrom:
          secretKeyRef:
            name: tempo-s3-secret
            key: S3_SECRET_KEY

    persistence:
      enabled: true
      storageClassName: ceph-block
      size: 10Gi

    serviceMonitor:
      enabled: true
