---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app whisper
spec:
  interval: 1h
  chartRef:
    kind: OCIRepository
    name: whisper
  maxHistory: 2
  install:
    remediation:
      retries: -1
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    controllers:
      whisper:
        type: statefulset
        annotations:
          reloader.stakater.com/auto: "true"
        containers:
          whisper:
            image:
              repository: rhasspy/wyoming-whisper
              tag: 3.6.0@sha256:b7da5869ac9caba5f8db1c0dec373fb46a58d31f4aee1855faa7b49b7c0d4b49
            args:
              - --model=small
              - --language=en
              - --data-dir=/data
            env:
              TZ: America/New_York
            resources:
              requests:
                cpu: 500m
                memory: 2Gi
              limits:
                memory: 4Gi
            securityContext:
              allowPrivilegeEscalation: false
              readOnlyRootFilesystem: true
              capabilities: { drop: ["ALL"] }
    defaultPodOptions:
      terminationGracePeriodSeconds: 10
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
        fsGroupChangePolicy: OnRootMismatch
    service:
      whisper:
        controller: *app
        type: LoadBalancer
        annotations:
          lbipam.cilium.io/ips: 192.168.29.103
        ports:
          http:
            port: 10300
            protocol: TCP
    persistence:
      data:
        existingClaim: "{{ .Release.Name }}"
      tmp:
        type: emptyDir
        medium: Memory
