---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/source.toolkit.fluxcd.io/ocirepository_v1.json
apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: kromgo
spec:
  interval: 15m
  layerSelector:
    mediaType: application/vnd.cncf.helm.chart.content.v1.tar+gzip
    operation: copy
  ref:
    tag: 0.16.1
    digest: sha256:aa48aa7d3afdce2102d22975f184b86d9333a882514048fd5c628b1bfec06745
  url: oci://ghcr.io/home-operations/charts/kromgo
