---
# yaml-language-server: $schema=https://kubernetes-schemas.dmfrey.com/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: tofu-controller

spec:

  chartRef:
    kind: OCIRepository
    name: tofu-controller

  interval: 1h

  values:

    allowCrossNamespaceRefs: true

    # installCRDs: true

    metrics:
      enabled: true
      serviceMonitor:
        enabled: true
        interval: 1m

    runner:
      image:
        repository: ghcr.io/flux-iac/tf-runner
        tag: v0.16.4@sha256:fc3af4d9b99f54cc92d4aec51d83117dcf373b79d8ed1dc6f69a4ac154184725
      serviceAccount:
        create: true
        allowedNamespaces:
          - download
          - media
          - security
