---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: rackpeek

spec:

  chartRef:
    kind: OCIRepository
    name: omni-tools

  interval: 1h

  values:

    controllers:
      rackpeek:

        containers:
          app:
            image:
              repository: aptacode/rackpeek
              tag: latest

            securityContext:
              allowPrivilegeEscalation: false
              readOnlyRootFilesystem: true
              capabilities: {drop: ["ALL"]}

    defaultPodOptions:
      securityContext:
        runAsNonRoot: true
        runAsUser: 1654
        runAsGroup: 1654
        fsGroup: 1654
        fsGroupChangePolicy: OnRootMismatch

    service:
      app:
        ports:
          http:
            port: 8080

    route:
      app:
        hostnames:
          - "{{ .Release.Name }}.dmfrey.com"
        parentRefs:
          - name: envoy-internal
            namespace: network

    persistence:
      config:
        existingClaim: "{{ .Release.Name }}"
        globalMounts:
          - path: /app/config

      yaml:
        type: configMap
        name: "{{ .Release.Name }}"
        globalMounts:
          - path: /app/config/config.yaml
            subPath: config.yaml

      tmpfs:
        type: emptyDir
        globalMounts:
          - path: /app/config/logs
            subPath: logs
          - path: /tmp
            subPath: tmp