---
# yaml-language-server: $schema=https://kubernetes-schemas.dmfrey.com/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: home-assistant-llmvision
spec:
  components:
    - ../../../../components/volsync
  dependsOn:
    - name: rook-ceph-cluster
      namespace: rook-ceph
  interval: 1h
  path: "./kubernetes/apps/home/home-assistant/home-assistant-llmvision"
  postBuild:
    substitute:
      APP: home-assistant-llmvision
      VOLSYNC_CAPACITY: 2Gi
    substituteFrom:
      - kind: Secret
        name: cluster-secrets
        optional: false
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  targetNamespace: home
  wait: false
---
# yaml-language-server: $schema=https://kubernetes-schemas.dmfrey.com/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: home-assistant-db
spec:
  dependsOn:
    - name: cloudnative-pg
      namespace: datastore
  healthChecks:
    - apiVersion: postgresql.cnpg.io/v1
      kind: Cluster
      name: home-assistant-cnpg
      namespace: home
  interval: 1h
  path: "./kubernetes/apps/home/home-assistant/home-assistant-db"
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  targetNamespace: home
  wait: false
---
# yaml-language-server: $schema=https://kubernetes-schemas.dmfrey.com/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: home-assistant
spec:
  components:
    - ../../../../components/volsync
  dependsOn:
    - name: home-assistant-db
    - name: mosquitto
    - name: multus-networks
      namespace: kube-system
    - name: rook-ceph-cluster
      namespace: rook-ceph
  interval: 1h
  path: "./kubernetes/apps/home/home-assistant/app"
  postBuild:
    substitute:
      APP: home-assistant
      VOLSYNC_CAPACITY: 5Gi
      VOLSYNC_CACHE_CAPACITY: 2Gi
    substituteFrom:
      - kind: Secret
        name: cluster-secrets
        optional: false
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  targetNamespace: home
  wait: false
