---
# yaml-language-server: $schema=https://kubernetes-schemas.dmfrey.com/source.toolkit.fluxcd.io/ocirepository_v1.json
apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: rook-ceph
spec:
  interval: 15m
  layerSelector:
    mediaType: application/vnd.cncf.helm.chart.content.v1.tar+gzip
    operation: copy
  ref:
    tag: v1.20.5
    digest: sha256:da9316fd7f8712b0278a9d6815818b12cf9412f063c1c86d1bec1b3eb900fcee
  url: oci://ghcr.io/rook/rook-ceph
