---
# yaml-language-server: $schema=https://kubernetes-schemas.dmfrey.com/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: opencode
spec:
  secretStoreRef:
    name: onepassword-connect
    kind: ClusterSecretStore
  refreshInterval: 15m
  target:
    name: opencode-secret
    template:
      engineVersion: v2
      data:
        OPENCODE_SERVER_PASSWORD: "{{ .OPENCODE_SERVER_PASSWORD }}"
  dataFrom:
    - extract:
        key: opencode
