---
name: "Terraform: Build OCI artifacts"

on: # yamllint disable-line rule:truthy
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - infrastructure/terraform/**

permissions:
  contents: read

jobs:
  changed-files:
    name: Generate matrix for building images
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
        with:
          persist-credentials: false

      - name: Setup Tools
        run: sudo apt-get install -y jo

      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@22103cc46bda19c2b464ffe86db46df6922fd323 # v47.0.5
        with:
          dir_names: true
          json: true
          files: |
            infrastructure/terraform/**

      - name: List all changed files
        run: |
          echo '${{ steps.changed-files.outputs.all_changed_files }}'

      - name: Store changed projects
        id: set-matrix
        run: |
          if [[ "${{ steps.changed-files.outputs.all_changed_files }}" == "[]" ]]; then
            echo "matrix={\"project\":$(find terraform -type f -name .terraform.lock.hcl | xargs dirname | jo -a)}" >> "${GITHUB_OUTPUT}"
          else
            echo "matrix={\"project\":${{ steps.changed-files.outputs.all_changed_files }}}" >> "${GITHUB_OUTPUT}"
          fi

  publish:
    runs-on: ubuntu-latest
    needs:
      - changed-files
    permissions:
      contents: read
      packages: write
    strategy:
      matrix: ${{ fromJSON(needs.changed-files.outputs.matrix) }}
    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
        with:
          persist-credentials: false

      - name: Setup Tools
        env:
          # renovate: datasource=github-releases depName=fluxcd/flux2
          FLUX_VERSION: v2.8.5
        run: |
          curl -sL "https://github.com/fluxcd/flux2/releases/download/${FLUX_VERSION}/flux_${FLUX_VERSION#v}_linux_amd64.tar.gz" \
            | sudo tar xz -C /usr/local/bin flux

      - name: Login to GitHub Container Registry
        uses: docker/login-action@4907a6ddec9925e35a0a9e82d7399ccc52663121 # v4
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Lowercase Owner Name
        env:
          REPO_OWNER: '${{ github.repository_owner }}'
        run: |
          echo "REPO_OWNER_LC=${REPO_OWNER,,}" >>${GITHUB_ENV}

      - name: Publish OCI
        run: |
          flux push artifact "oci://ghcr.io/${REPO_OWNER_LC}/terraform/$(basename ${{ matrix.project }}):$(git rev-parse --short HEAD)" \
            --path="./${{ matrix.project }}" \
            --source="$(git config --get remote.origin.url)" \
            --revision="$(git branch --show-current)/$(git rev-parse HEAD)"

      - name: Tag OCI
        run: |-
          flux tag artifact "oci://ghcr.io/${REPO_OWNER_LC}/terraform/$(basename ${{ matrix.project }}):$(git rev-parse --short HEAD)" \
            --tag main
